import { describe, expect, it } from 'vitest';
import {
    buildSpecialNotesFromImportantHandoffs,
    hasAutoGeneratedContent,
    removeAutoGeneratedContent,
    shouldAutoGenerateSpecialNotes,
    type ImportantHandoffForDaily
} from '../useImportantHandoffsForDaily';

describe('useImportantHandoffsForDaily utilities', () => {
  const mockHandoffs: ImportantHandoffForDaily[] = [
    {
      id: 1,
      userId: '001',
      personDisplayName: '田中太郎',
      date: '2025-11-18',
      time: '09:30',
      category: '体調',
      severity: '重要',
      message: '血圧が高めで注意が必要',
      timeBand: '午前',
      status: '未対応'
    },
    {
      id: 2,
      userId: '001',
      personDisplayName: '田中太郎',
      date: '2025-11-18',
      time: '14:15',
      category: '行動面',
      severity: '重要',
      message: '他利用者との衝突があった',
      timeBand: '午後',
      status: '対応中'
    }
  ];

  describe('buildSpecialNotesFromImportantHandoffs', () => {
    it('should generate formatted special notes from handoffs', () => {
      const result = buildSpecialNotesFromImportantHandoffs(mockHandoffs);

      expect(result).toContain('【申し送り（重要）から自動転記】');
      expect(result).toContain('・⚠️ 09:30 体調：血圧が高めで注意が必要');
      expect(result).toContain('・🔄 14:15 行動面：他利用者との衝突があった');
    });

    it('should append to existing notes', () => {
      const existing = '手動で入力された特記事項';
      const result = buildSpecialNotesFromImportantHandoffs(mockHandoffs, existing);

      expect(result).toContain(existing);
      expect(result).toContain('【申し送り（重要）から自動転記】');
    });

    it('should return existing notes when no handoffs', () => {
      const existing = '既存の特記事項';
      const result = buildSpecialNotesFromImportantHandoffs([], existing);

      expect(result).toBe(existing);
    });
  });

  describe('shouldAutoGenerateSpecialNotes', () => {
    it('should return true for new record with important handoffs', () => {
      const result = shouldAutoGenerateSpecialNotes(true, '001', '', 2);
      expect(result).toBe(true);
    });

    it('should return false for edit mode', () => {
      const result = shouldAutoGenerateSpecialNotes(false, '001', '', 2);
      expect(result).toBe(false);
    });

    it('should return false when no person selected', () => {
      const result = shouldAutoGenerateSpecialNotes(true, '', '', 2);
      expect(result).toBe(false);
    });

    it('should return false when special notes already exist', () => {
      const result = shouldAutoGenerateSpecialNotes(true, '001', '既存の特記事項', 2);
      expect(result).toBe(false);
    });

    it('should return false when no important handoffs', () => {
      const result = shouldAutoGenerateSpecialNotes(true, '001', '', 0);
      expect(result).toBe(false);
    });
  });

  describe('hasAutoGeneratedContent', () => {
    it('should detect auto-generated content', () => {
      const text = `手動入力

【申し送り（重要）から自動転記】
・⚠️ 09:30 体調：血圧が高めで注意が必要`;

      const result = hasAutoGeneratedContent(text);
      expect(result).toBe(true);
    });

    it('should return false for manual content only', () => {
      const text = '手動で入力された特記事項のみ';
      const result = hasAutoGeneratedContent(text);
      expect(result).toBe(false);
    });
  });

  describe('removeAutoGeneratedContent', () => {
    it('should remove auto-generated content', () => {
      const text = `手動入力の特記事項

【申し送り（重要）から自動転記】
・⚠️ 09:30 体調：血圧が高めで注意が必要
・🔄 14:15 行動面：他利用者との衝突があった`;

      const result = removeAutoGeneratedContent(text);
      expect(result).toBe('手動入力の特記事項');
    });

    it('should return original text when no auto-generated content', () => {
      const text = '手動で入力された特記事項のみ';
      const result = removeAutoGeneratedContent(text);
      expect(result).toBe(text);
    });
  });
});