/* eslint-disable no-console -- CLI ops script */
/**
 * renderIssueDraftMarkdown — Issue Draft 配列を Markdown に整形する
 *
 * @see .agents/workflows/nightly.md
 */

const SEVERITY_EMOJI = {
  critical: '🔴',
  high: '🟠',
  medium: '🟡',
  low: '🟢',
};

/**
 * 1つの Issue Draft を Markdown セクションに変換
 *
 * @param {object} draft
 * @param {number} index - 1-based
 * @returns {string}
 */
function renderSingleDraft(draft, index) {
  const emoji = SEVERITY_EMOJI[draft.severity] || '⚪';
  const lines = [];

  lines.push(`## ${index}. ${emoji} [${draft.severity}] ${draft.title}`);
  lines.push('');

  // 背景
  lines.push('### 背景');
  lines.push('');
  lines.push(draft.rationale);
  lines.push('');

  // 現状
  lines.push('### 現状');
  lines.push('');
  lines.push(draft.summary);
  lines.push('');

  // 対象ファイル
  if (draft.targetFiles.length > 0) {
    lines.push('### 対象ファイル');
    lines.push('');
    for (const f of draft.targetFiles) {
      lines.push(`- \`${f}\``);
    }
    lines.push('');
  }

  // 提案
  if (draft.proposal.length > 0) {
    lines.push('### 提案');
    lines.push('');
    for (const p of draft.proposal) {
      lines.push(`- ${p}`);
    }
    lines.push('');
  }

  // 受入条件
  if (draft.acceptanceCriteria.length > 0) {
    lines.push('### 受入条件');
    lines.push('');
    for (const c of draft.acceptanceCriteria) {
      lines.push(`- [ ] ${c}`);
    }
    lines.push('');
  }

  // Labels
  if (draft.labels && draft.labels.length > 0) {
    lines.push(`**Labels:** ${draft.labels.map((l) => `\`${l}\``).join(', ')}`);
    lines.push('');
  }

  lines.push('---');
  lines.push('');

  return lines.join('\n');
}

/**
 * Issue Draft 配列を完全な Markdown ドキュメントに変換
 *
 * @param {Array<object>} drafts - buildIssueDrafts の出力
 * @param {string} dateStamp - YYYY-MM-DD
 * @returns {string} Markdown
 */
export function renderIssueDraftMarkdown(drafts, dateStamp) {
  const lines = [];

  lines.push(`# 📋 Nightly Issue Drafts — ${dateStamp}`);
  lines.push('');
  lines.push(`> Generated by nightly-patrol Phase B — ${dateStamp}`);
  lines.push('');

  if (drafts.length === 0) {
    lines.push('## ✅ Issue Draft なし');
    lines.push('');
    lines.push('すべての品質指標が閾値以内です。対応不要。');
    lines.push('');
    lines.push('---');
    lines.push('');
    lines.push('*Generated by Nightly Patrol (Phase B) — Issue Draft Generator*');
    return lines.join('\n');
  }

  // サマリーテーブル
  lines.push('## サマリー');
  lines.push('');
  lines.push(`| # | Severity | Category | Title |`);
  lines.push(`|:-:|:--------:|----------|-------|`);
  drafts.forEach((d, i) => {
    const emoji = SEVERITY_EMOJI[d.severity] || '⚪';
    lines.push(`| ${i + 1} | ${emoji} ${d.severity} | ${d.category} | ${d.title} |`);
  });
  lines.push('');

  // 統計
  const bySeverity = {};
  for (const d of drafts) {
    bySeverity[d.severity] = (bySeverity[d.severity] || 0) + 1;
  }
  lines.push(`**合計:** ${drafts.length} 件`);
  const parts = [];
  if (bySeverity.critical) parts.push(`🔴 critical: ${bySeverity.critical}`);
  if (bySeverity.high) parts.push(`🟠 high: ${bySeverity.high}`);
  if (bySeverity.medium) parts.push(`🟡 medium: ${bySeverity.medium}`);
  if (bySeverity.low) parts.push(`🟢 low: ${bySeverity.low}`);
  if (parts.length > 0) lines.push(`(${parts.join(' / ')})`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // 各 Draft
  drafts.forEach((d, i) => {
    lines.push(renderSingleDraft(d, i + 1));
  });

  // Usage hint
  lines.push('## 使い方');
  lines.push('');
  lines.push('1. 上記の Draft を確認し、対応が必要なものを選ぶ');
  lines.push('2. GitHub Issue として起票する（タイトル・本文をコピー）');
  lines.push('3. 対応するワークフロー (`/refactor`, `/review`, `/test-design`) を実行');
  lines.push('');
  lines.push('> ⚠️ この Draft は自動生成です。内容を確認してから起票してください。');
  lines.push('');

  lines.push('---');
  lines.push('');
  lines.push('*Generated by Nightly Patrol (Phase B) — Issue Draft Generator*');

  return lines.join('\n');
}
