import { motionTokens } from '@/app/theme';
import { DailyStatus, PersonDaily } from '@/features/daily';
import { hasAutoGeneratedContent } from '@/features/handoff';
import { BEHAVIOR_TAGS, type BehaviorTagKey } from '../domain/behaviorTag';
import AccessTimeIcon from '@mui/icons-material/AccessTime';
import CheckCircleIcon from '@mui/icons-material/CheckCircle';
import DeleteIcon from '@mui/icons-material/Delete';
import EditIcon from '@mui/icons-material/Edit';
import MoreVertIcon from '@mui/icons-material/MoreVert';
import NotificationsIcon from '@mui/icons-material/Notifications';
import LocalOfferIcon from '@mui/icons-material/LocalOffer';
import PersonIcon from '@mui/icons-material/Person';
import RestaurantIcon from '@mui/icons-material/Restaurant';
import WarningIcon from '@mui/icons-material/Warning';
import Avatar from '@mui/material/Avatar';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';
import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import Chip from '@mui/material/Chip';
import MuiDialog from '@mui/material/Dialog';
import DialogActions from '@mui/material/DialogActions';
import DialogContent from '@mui/material/DialogContent';
import DialogContentText from '@mui/material/DialogContentText';
import DialogTitle from '@mui/material/DialogTitle';
import Divider from '@mui/material/Divider';
import IconButton from '@mui/material/IconButton';
import Menu from '@mui/material/Menu';
import MenuItem from '@mui/material/MenuItem';
import Stack from '@mui/material/Stack';
import Typography from '@mui/material/Typography';
import React from 'react';

interface DailyRecordListProps {
  records: PersonDaily[];
  onEdit: (record: PersonDaily) => void;
  onDelete: (recordId: number) => void;
  onOpenAttendance?: (record: PersonDaily) => void;
  onOpenHandoffTimeline?: (record: PersonDaily) => void; // Phase 9: 申し送り表示用
  loading?: boolean;
  highlightUserId?: string | null;
  highlightDate?: string | null;
  activeHighlightUserId?: string | null; // Phase 2-1: 一時ハイライト表示用
}

const statusColors: Record<DailyStatus, 'default' | 'primary' | 'secondary' | 'success' | 'error' | 'info' | 'warning'> = {
  '未作成': 'default',
  '作成中': 'warning',
  '完了': 'success'
};

const statusIcons: Record<DailyStatus, React.ReactElement> = {
  '未作成': <WarningIcon fontSize="small" />,
  '作成中': <AccessTimeIcon fontSize="small" />,
  '完了': <CheckCircleIcon fontSize="small" />
};

export function DailyRecordList({
  records,
  onEdit,
  onDelete,
  onOpenAttendance,
  onOpenHandoffTimeline, // Phase 9: 申し送り表示用
  loading = false,
  highlightUserId,
  highlightDate,
  activeHighlightUserId // Phase 2-1: 一時ハイライト表示用
}: DailyRecordListProps) {
  const [anchorEl, setAnchorEl] = React.useState<null | HTMLElement>(null);
  const [selectedRecord, setSelectedRecord] = React.useState<PersonDaily | null>(null);
  // P0防波堤: 削除確認ダイアログ用
  const [deleteConfirmRecord, setDeleteConfirmRecord] = React.useState<PersonDaily | null>(null);

  // Utility function for meal amount formatting
  const formatMealAmount = (amount: PersonDaily['data']['mealAmount']) => {
    if (!amount) return '完食';
    return amount;
  };

  const handleMenuOpen = (event: React.MouseEvent<HTMLElement>, record: PersonDaily) => {
    setAnchorEl(event.currentTarget);
    setSelectedRecord(record);
  };

  const handleMenuClose = () => {
    setAnchorEl(null);
    setSelectedRecord(null);
  };

  const handleEdit = () => {
    if (selectedRecord) {
      onEdit(selectedRecord);
    }
    handleMenuClose();
  };

  // P0防波堤: 削除メニュークリック時は確認ダイアログを表示
  const handleDelete = () => {
    if (selectedRecord) {
      setDeleteConfirmRecord(selectedRecord);
    }
    handleMenuClose();
  };

  const handleConfirmDelete = () => {
    if (deleteConfirmRecord) {
      onDelete(deleteConfirmRecord.id);
    }
    setDeleteConfirmRecord(null);
  };

  const handleCancelDelete = () => {
    setDeleteConfirmRecord(null);
  };

  const handleOpenAttendance = () => {
    if (selectedRecord && onOpenAttendance) {
      onOpenAttendance(selectedRecord);
    }
    handleMenuClose();
  };

  // Phase 9: 申し送り表示ハンドラー
  const handleOpenHandoffTimeline = () => {
    if (selectedRecord && onOpenHandoffTimeline) {
      onOpenHandoffTimeline(selectedRecord);
    }
    handleMenuClose();
  };

  if (loading) {
    return (
      <Box sx={{ textAlign: 'center', py: 4 }} data-testid="daily-record-list-loading">
        <Typography variant="body2" color="text.secondary">
          読み込み中...
        </Typography>
      </Box>
    );
  }

  if (records.length === 0) {
    return (
      <Box sx={{ textAlign: 'center', py: 4 }} data-testid="daily-record-list-empty">
        <Typography variant="body2" color="text.secondary">
          まだ日々の記録がありません
        </Typography>
      </Box>
    );
  }

  return (
    <>
      <Stack spacing={2} data-testid="daily-record-list-container">
        {records.map((record) => {
          // Phase 2-1: Check if this record should be highlighted
          const isHighlighted =
            !!highlightUserId &&
            !!highlightDate &&
            record.userId === highlightUserId &&
            record.date === highlightDate;

          // Phase 2-1: 一時ハイライト（スクロール直後）
          const isActiveHighlight = activeHighlightUserId === record.userId;

          // Check for problem behaviors
          const hasProblemBehavior =
            !!record.data.problemBehavior &&
            (
              record.data.problemBehavior.selfHarm ||
              record.data.problemBehavior.otherInjury ||
              record.data.problemBehavior.loudVoice ||
              record.data.problemBehavior.pica ||
              record.data.problemBehavior.other
            );

          return (
            <Card
              key={record.id}
              variant="outlined"
              data-testid={`daily-record-card-${record.id}`}
              data-person-id={record.userId}
              data-date-ymd={record.date}
              {...(isHighlighted && {
                'data-highlighted': 'true',
              })}
              sx={{
                ...(isHighlighted && {
                  borderColor: 'primary.main',
                  boxShadow: 4,
                  backgroundColor: 'rgba(25, 118, 210, 0.04)',
                }),
                ...(isActiveHighlight && {
                  outline: '3px solid',
                  outlineColor: 'warning.main',
                  transition: `outline ${motionTokens.duration.normal} ${motionTokens.easing.standard}`,
                }),
              }}
            >
            <CardContent>
              {/* Phase 2-1: ハイライトバナー */}
              {isActiveHighlight && (
                <Box
                  sx={{
                    mb: 2,
                    p: 1,
                    bgcolor: 'warning.50',
                    borderRadius: 1,
                    border: '1px solid',
                    borderColor: 'warning.200',
                  }}
                  data-testid="daily-highlight-banner"
                >
                  <Typography variant="caption" sx={{ fontWeight: 600, color: 'warning.dark' }}>
                    📌 申し送りから移動しました
                  </Typography>
                </Box>
              )}

              {/* ヘッダー部分 */}
              <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', mb: 2 }}>
                <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }} data-testid={`record-header-${record.id}`}>
                  <Avatar sx={{ width: 32, height: 32, bgcolor: 'primary.main' }}>
                    <PersonIcon fontSize="small" />
                  </Avatar>
                  <Box>
                    <Typography variant="subtitle1" sx={{ fontWeight: 'bold' }} data-testid={`person-name-${record.id}`}>
                      {record.userName}
                    </Typography>
                    <Typography variant="caption" color="text.secondary" data-testid={`person-id-${record.id}`}>
                      ID: {record.userId}
                    </Typography>
                  </Box>
                </Box>

                <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                  <Chip
                    icon={statusIcons[record.status]}
                    label={record.status}
                    color={statusColors[record.status]}
                    size="small"
                    data-testid={`status-chip-${record.id}`}
                  />
                  <IconButton
                    size="small"
                    onClick={(e) => handleMenuOpen(e, record)}
                    data-testid={`menu-button-${record.id}`}
                    aria-label={`${record.userName}さんのメニューを開く`}
                    aria-haspopup="menu"
                  >
                    <MoreVertIcon />
                  </IconButton>
                </Box>
              </Box>

              {/* 基本情報 */}
              <Stack direction="row" spacing={2} sx={{ mb: 2 }}>
                <Typography variant="body2">
                  <strong>日付:</strong> {record.date}
                </Typography>
                <Typography variant="body2">
                  <strong>記録者:</strong> {record.reporter.name}
                </Typography>
              </Stack>

              <Divider sx={{ my: 2 }} />

              {/* 活動情報 */}
              <Box sx={{ mb: 2 }}>
                <Typography variant="subtitle2" sx={{ mb: 1, display: 'flex', alignItems: 'center', gap: 0.5 }}>
                  <AccessTimeIcon fontSize="small" />
                  活動記録
                </Typography>

                {record.data.amActivities.length > 0 && (
                  <Box sx={{ mb: 1 }}>
                    <Typography variant="caption" color="text.secondary">午前:</Typography>
                    <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 0.5, mt: 0.5 }}>
                      {record.data.amActivities.map((activity: string, index: number) => (
                        <Chip
                          key={index}
                          label={activity}
                          size="small"
                          variant="outlined"
                        />
                      ))}
                    </Box>
                  </Box>
                )}

                {record.data.pmActivities.length > 0 && (
                  <Box sx={{ mb: 1 }}>
                    <Typography variant="caption" color="text.secondary">午後:</Typography>
                    <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 0.5, mt: 0.5 }}>
                      {record.data.pmActivities.map((activity: string, index: number) => (
                        <Chip
                          key={index}
                          label={activity}
                          size="small"
                          variant="outlined"
                        />
                      ))}
                    </Box>
                  </Box>
                )}
              </Box>

              {/* 食事情報 */}
              <Box sx={{ mb: 2 }}>
                <Typography variant="subtitle2" sx={{ mb: 1, display: 'flex', alignItems: 'center', gap: 0.5 }}>
                  <RestaurantIcon fontSize="small" />
                  食事記録
                </Typography>
                <Chip
                  label={`食事摂取量: ${formatMealAmount(record.data.mealAmount)}`}
                  size="small"
                  color="primary"
                  variant="outlined"
                />
              </Box>

              {/* 問題行動 */}
              {hasProblemBehavior && (
                <Box sx={{ mb: 2 }}>
                  <Stack direction="row" spacing={1} flexWrap="wrap">
                    {record.data.problemBehavior?.selfHarm && (
                      <Chip label="自傷" size="small" color="warning" />
                    )}
                    {record.data.problemBehavior?.otherInjury && (
                      <Chip label="他傷" size="small" color="warning" />
                    )}
                    {record.data.problemBehavior?.loudVoice && (
                      <Chip label="大声" size="small" color="warning" />
                    )}
                    {record.data.problemBehavior?.pica && (
                      <Chip label="異食" size="small" color="warning" />
                    )}
                    {record.data.problemBehavior?.other && (
                      <Chip label="その他" size="small" color="warning" />
                    )}
                  </Stack>
                </Box>
              )}

              {/* 行動タグ (MVP-004) */}
              {(record.data.behaviorTags?.length ?? 0) > 0 && (
                <Box sx={{ mb: 2 }} data-testid={`behavior-tags-display-${record.id}`}>
                  <Typography variant="subtitle2" sx={{ mb: 0.5, display: 'flex', alignItems: 'center', gap: 0.5 }}>
                    <LocalOfferIcon fontSize="small" />
                    行動タグ
                  </Typography>
                  <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 0.5 }}>
                    {(record.data.behaviorTags ?? []).map((tagKey: string) => {
                      const tag = BEHAVIOR_TAGS[tagKey as BehaviorTagKey];
                      return (
                        <Chip
                          key={tagKey}
                          label={tag?.label ?? tagKey}
                          size="small"
                          variant="outlined"
                          color="primary"
                        />
                      );
                    })}
                  </Box>
                </Box>
              )}

              {/* 発作記録 */}
              {record.data.seizureRecord?.occurred && (
                <Box sx={{ mb: 2 }}>
                  <Chip
                    label={`発作あり${record.data.seizureRecord.severity ? ` (${record.data.seizureRecord.severity})` : ''}`}
                    size="small"
                    color="error"
                    icon={<WarningIcon />}
                  />
                </Box>
              )}

              {/* 法的記録: 拘束・別紙 */}
              {(record.data.restraint || record.data.hasAttachment) && (
                <Box sx={{ mb: 2 }}>
                  <Stack direction="row" spacing={1}>
                    {record.data.restraint && (
                      <Chip label="拘束あり" size="small" color="error" />
                    )}
                    {record.data.hasAttachment && (
                      <Chip label="別紙あり" size="small" color="info" variant="outlined" />
                    )}
                  </Stack>
                </Box>
              )}

              {/* 特記事項 */}
              {record.data.specialNotes && (
                <Box>
                  <Typography variant="subtitle2" sx={{ mb: 1, display: 'flex', alignItems: 'center', gap: 0.5 }}>
                    特記事項
                    {/* Phase 9: 申し送り自動転記表示 */}
                    {hasAutoGeneratedContent(record.data.specialNotes) && (
                      <Chip
                        label="申し送り連携"
                        size="small"
                        color="info"
                        icon={<NotificationsIcon />}
                        variant="outlined"
                      />
                    )}
                  </Typography>
                  <Typography variant="body2" color="text.secondary" sx={{ whiteSpace: 'pre-line' }}>
                    {record.data.specialNotes}
                  </Typography>
                </Box>
              )}

              {/* メモ */}
              {(record.data.amNotes || record.data.pmNotes) && (
                <Box sx={{ mt: 2 }}>
                  {record.data.amNotes && (
                    <Typography variant="caption" display="block" color="text.secondary">
                      午前メモ: {record.data.amNotes}
                    </Typography>
                  )}
                  {record.data.pmNotes && (
                    <Typography variant="caption" display="block" color="text.secondary">
                      午後メモ: {record.data.pmNotes}
                    </Typography>
                  )}
                </Box>
              )}
            </CardContent>
          </Card>
          );
        })}
      </Stack>

      {/* コンテキストメニュー */}
      <Menu
        anchorEl={anchorEl}
        open={Boolean(anchorEl)}
        onClose={handleMenuClose}
        data-testid="record-menu"
        MenuListProps={{
          'aria-label': `${selectedRecord?.userName || ''}さんの操作メニュー`,
        }}
      >
        <MenuItem onClick={handleEdit} data-testid={`edit-record-menu-item-${selectedRecord?.id || ''}`}>
          <EditIcon fontSize="small" sx={{ mr: 1 }} />
          編集
        </MenuItem>
        {/* ★ 追加: 通所管理へのクロスリンク */}
        {onOpenAttendance && (
          <MenuItem onClick={handleOpenAttendance} data-testid={`attendance-link-from-activity-${selectedRecord?.id || ''}`}>
            <PersonIcon fontSize="small" sx={{ mr: 1 }} />
            通所状況を見る
          </MenuItem>
        )}
        {/* Phase 9: 申し送りタイムライン表示 */}
        {onOpenHandoffTimeline && (
          <MenuItem onClick={handleOpenHandoffTimeline} data-testid={`handoff-timeline-link-${selectedRecord?.id || ''}`}>
            <NotificationsIcon fontSize="small" sx={{ mr: 1 }} />
            申し送りを見る
          </MenuItem>
        )}
        <MenuItem onClick={handleDelete} sx={{ color: 'error.main' }} data-testid={`delete-record-menu-item-${selectedRecord?.id || ''}`}>
          <DeleteIcon fontSize="small" sx={{ mr: 1 }} />
          削除
        </MenuItem>
      </Menu>

      {/* P0防波堤: 削除確認ダイアログ */}
      <MuiDialog
        open={deleteConfirmRecord !== null}
        onClose={handleCancelDelete}
        data-testid="delete-confirm-dialog"
        aria-labelledby="delete-confirm-title"
      >
        <DialogTitle id="delete-confirm-title">記録の削除</DialogTitle>
        <DialogContent>
          <DialogContentText>
            {deleteConfirmRecord?.userName}さんの記録（{deleteConfirmRecord?.date}）を削除します。
            この操作は取り消せません。
          </DialogContentText>
        </DialogContent>
        <DialogActions>
          <Button
            onClick={handleCancelDelete}
            data-testid="delete-cancel-button"
          >
            キャンセル
          </Button>
          <Button
            onClick={handleConfirmDelete}
            color="error"
            variant="contained"
            data-testid="delete-confirm-button"
          >
            削除する
          </Button>
        </DialogActions>
      </MuiDialog>
    </>
  );
}
