import { useEffect, useState } from 'react';
import type { HandoffDayScope, HandoffRecord } from '../handoffTypes';
import { useHandoffTimeline } from '../useHandoffTimeline';

/**
 * 日次記録用の重要申し送り情報
 */
export interface ImportantHandoffForDaily {
  id: string | number;
  personId: string;
  personDisplayName: string;
  date: string;      // 'YYYY-MM-DD'
  time: string;      // 'HH:mm' 時刻表示用
  category: string;  // '体調', '行動面', ...
  severity: '通常' | '要注意' | '重要';
  message: string;
  timeBand: string;  // '朝', '午前', '午後', '夕方'
  status: string;    // '未対応', '対応中', '対応済'
}

/**
 * 日次記録作成時に重要な申し送り情報を取得するフック
 *
 * @param personId 対象利用者のID
 * @param date 対象日付（YYYY-MM-DD）
 * @returns 重要度「重要」の申し送りのみ
 */
export function useImportantHandoffsForDaily(personId: string, date: string) {
  const [importantHandoffs, setImportantHandoffs] = useState<ImportantHandoffForDaily[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // 日付からdayScopeを決定
  const today = new Date().toISOString().split('T')[0]; // YYYY-MM-DD
  const yesterday = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString().split('T')[0];

  let dayScope: HandoffDayScope = 'today';
  if (date === yesterday) {
    dayScope = 'yesterday';
  } else if (date !== today) {
    dayScope = 'week'; // 過去日は週スコープで取得
  }

  const {
    todayHandoffs: allHandoffs,
    loading: handoffsLoading,
    error: handoffsError
  } = useHandoffTimeline('all', dayScope);

  useEffect(() => {
    setLoading(handoffsLoading);
    setError(handoffsError);

    if (!handoffsLoading && !handoffsError && allHandoffs) {
      // 指定された利用者 + 重要度「重要」のみを抽出
      const filtered = allHandoffs
        .filter(handoff => {
          // 利用者IDマッチング（userCode または personId で照合）
          const userMatch = handoff.userCode === personId ||
                           handoff.userDisplayName.includes(personId);

          // 重要度フィルタ
          const severityMatch = handoff.severity === '重要';

          return userMatch && severityMatch;
        })
        .map(handoff => convertToImportantHandoff(handoff));

      setImportantHandoffs(filtered);
    } else {
      setImportantHandoffs([]);
    }
  }, [personId, date, allHandoffs, handoffsLoading, handoffsError]);

  return {
    items: importantHandoffs,
    loading,
    error,
    count: importantHandoffs.length,
  };
}

/**
 * HandoffRecord を ImportantHandoffForDaily に変換
 */
function convertToImportantHandoff(handoff: HandoffRecord): ImportantHandoffForDaily {
  // 作成時刻から時刻文字列を生成
  const createdAt = new Date(handoff.createdAt);
  const time = `${createdAt.getHours().toString().padStart(2, '0')}:${createdAt.getMinutes().toString().padStart(2, '0')}`;
  const date = createdAt.toISOString().split('T')[0]; // YYYY-MM-DD

  return {
    id: handoff.id,
    personId: handoff.userCode,
    personDisplayName: handoff.userDisplayName,
    date,
    time,
    category: handoff.category,
    severity: handoff.severity as '通常' | '要注意' | '重要',
    message: handoff.message,
    timeBand: handoff.timeBand,
    status: handoff.status,
  };
}

/**
 * 重要な申し送りから特記事項用のテキストを生成
 *
 * @param handoffs 重要な申し送りリスト
 * @param existing 既存の特記事項テキスト
 * @returns 整形された特記事項テキスト
 */
export function buildSpecialNotesFromImportantHandoffs(
  handoffs: ImportantHandoffForDaily[],
  existing = ''
): string {
  if (!handoffs || handoffs.length === 0) {
    return existing;
  }

  const header = '【申し送り（重要）から自動転記】';

  // 時刻順にソート（古い順）
  const sortedHandoffs = [...handoffs].sort((a, b) => a.time.localeCompare(b.time));

  const lines = sortedHandoffs.map(handoff => {
    const statusIcon = getStatusIcon(handoff.status);
    const timePart = `${handoff.time}`;
    const categoryPart = handoff.category ? `${handoff.category}：` : '';

    return `・${statusIcon} ${timePart} ${categoryPart}${handoff.message}`;
  });

  const autoGeneratedBlock = [header, ...lines].join('\n');

  // 既存の特記事項がある場合は、下に追加
  if (existing && existing.trim().length > 0) {
    return `${existing.trim()}\n\n${autoGeneratedBlock}`;
  }

  // 空なら、自動生成ブロックのみ
  return autoGeneratedBlock;
}

/**
 * 申し送りステータスに応じたアイコンを返す
 */
function getStatusIcon(status: string): string {
  switch (status) {
    case '未対応':
      return '⚠️';
    case '対応中':
      return '🔄';
    case '対応済':
      return '✅';
    default:
      return '📝';
  }
}

/**
 * 申し送りから特記事項への自動転記が有効かチェック
 */
export function shouldAutoGenerateSpecialNotes(
  isNewRecord: boolean,
  personId: string,
  currentSpecialNotes: string,
  importantHandoffsCount: number
): boolean {
  return (
    isNewRecord &&                                    // 新規作成時のみ
    Boolean(personId) &&                             // 利用者が選択済み
    importantHandoffsCount > 0 &&                    // 重要な申し送りが存在
    (!currentSpecialNotes || currentSpecialNotes.trim() === '')  // 特記事項が空
  );
}

/**
 * 自動転記された特記事項かどうかを判定
 */
export function hasAutoGeneratedContent(text: string): boolean {
  return text.includes('【申し送り（重要）から自動転記】');
}

/**
 * 自動転記部分を除去して元の特記事項のみを返す
 */
export function removeAutoGeneratedContent(text: string): string {
  const headerIndex = text.indexOf('【申し送り（重要）から自動転記】');
  if (headerIndex === -1) {
    return text;
  }

  // ヘッダー前の部分のみを返す
  const beforeHeader = text.substring(0, headerIndex).trim();
  return beforeHeader;
}