/**
 * All explicit route paths defined in this application.
 * Extracted here as a single source of truth for Nav <-> Router consistency tests
 * and the Diagnostics UI.
 */
export const APP_ROUTE_PATHS = [
  'auth/callback',
  'dashboard',
  'admin/dashboard',
  'dashboard/briefing',
  'today',
  'room-management',
  'meeting-guide',
  'compliance',
  'support-plan-guide',
  'isp-editor',
  'isp-editor/:userId',
  'handoff-timeline',
  'meeting-minutes',
  'meeting-minutes/new',
  'meeting-minutes/:id',
  'meeting-minutes/:id/edit',
  'records',
  'records/monthly',
  'billing',
  'checklist',
  'audit',
  'users',
  'users/new',
  'users/:userId',
  'staff',
  'staff/new',
  'staff/attendance',
  'staff/:staffId',
  'daily',
  'dailysupport',
  'daily/menu',
  'daily/table',
  'daily/activity',
  'daily/attendance',
  'daily/support',
  'daily/support-checklist',
  'daily/time-based',
  'daily/health',
  'analysis',
  'analysis/dashboard',
  'analysis/iceberg-pdca',
  'analysis/iceberg-pdca/edit',
  'analysis/iceberg',
  'assessment',
  'survey/tokusei',
  'admin/templates',
  'admin/step-templates',
  'admin/individual-support',
  'admin/staff-attendance',
  'admin/integrated-resource-calendar',
  'admin/navigation-diagnostics',
  'schedule',
  'schedule/*',
  'schedules',
  'schedules/week',
  'schedules/day',
  'schedules/month',
  'schedules/timeline',
  'schedules/unified',
  'schedules/create',
  'dev/schedule-create-dialog',
  'ibd',
] as const;

export type AppRoutePath = typeof APP_ROUTE_PATHS[number];
