import type { SupportPlanningSheet } from '@/domain/isp/schema/ispPlanningSheetSchema';

/**
 * 石渡 由喜子さんの「重度加算（外出入り）」の17行構成データ
 * 17行標準手順モデルの実務適合性検証用フィクスチャ
 */
export const ISHIWATA_SEVERE_SUPPORT_SHEET: SupportPlanningSheet = {
  id: 'ishiwata-severe-sheet',
  userId: 'U-003', // 新規ユーザーID
  ispId: 'isp-ishiwata-001',
  title: '石渡 由喜子 支援手順書（重度加算対応）',
  version: 1,
  targetScene: '日中活動',
  targetDomain: '生活全般',
  supportPolicy: '本人のペースを尊重し、状況に合わせた適時・適切な介助を行う。',
  environmentalAdjustments: '個別のタイミングを考慮した声掛けと、手洗い・消毒用の設備配置。',
  concreteApproaches: '朝のグループホーム（GH）からの連絡ノートの確認と、こまめな情報共有。',
  observationFacts: '自発的な排泄要望がないため、こまめな支援者間の情報共有が必要。',
  interpretationHypothesis: '決まった時間への誘導や、個別の行動観察に基づく声掛けにより、排泄失敗を予防できる。',
  supportIssues: '自発的な表出が難しい活動や生理的欲求（排泄等）に対する適時の声掛けと介助。',
  collectedInformation: 'グループホームからの連絡ノート、前年度の計画書、日々の様子。',
  planning: {
    procedureSteps: [
      {
        order: 1,
        timing: '09:30頃',
        instruction: '通所 朝の準備',
        staff: '',
        activityDetail: '送迎車で来所 手洗い 荷物の片づけ',
        instructionDetail: '送迎担当と引継ぎ ご本人と朝の準備（手洗い・荷物をロッカーへ） トイレ誘導・介助',
        condition: '',
      },
      {
        order: 2,
        timing: '10:00頃',
        instruction: '体操',
        staff: '',
        activityDetail: 'ラジオ体操参加 又はのんびり',
        instructionDetail: '見守り 状況に応じて体操の有無によっては補助又は介助。',
        condition: '',
      },
      {
        order: 3,
        timing: '10:10頃',
        instruction: 'スケジュール確認',
        staff: '',
        activityDetail: '発表時は室内（第1作業室にいる）',
        instructionDetail: '室内（第一作業室にいてもらうようにする。） 見守り',
        condition: '',
      },
      {
        order: 4,
        timing: '10:15頃',
        instruction: 'お茶休憩',
        staff: '',
        activityDetail: '手洗い、消毒後お茶を飲む',
        instructionDetail: '状況に応じて、手洗い、消毒、お茶を飲む補助又は介助',
        condition: '',
      },
      {
        order: 5,
        timing: '10:20〜12:00',
        instruction: 'AM日中活動',
        staff: '',
        activityDetail: '第二作業室で本や小道具でリラックス 室内や廊下を歩く',
        instructionDetail: '活動準備 トイレ誘導・介助 見守り',
        condition: '',
      },
      {
        order: 6,
        timing: '12:00',
        instruction: '昼食準備',
        staff: '',
        activityDetail: '手洗い、消毒 昼食まで座っている',
        instructionDetail: '状況により手洗い、消毒の補助又は介助 席についている見守り',
        condition: '',
      },
      {
        order: 7,
        timing: '12:10〜12:40',
        instruction: '昼食',
        staff: '',
        activityDetail: '食事の受取り 食事の片づけ、手洗い',
        instructionDetail: '状況により受取り、食事、片づけ、手洗いの補助又は介助',
        condition: '',
      },
      {
        order: 8,
        timing: '12:40〜13:45',
        instruction: '昼休み',
        staff: '',
        activityDetail: '動画鑑賞 コーヒー注文 のんびり過ごす',
        instructionDetail: 'タブレットの順番管理 コーヒーの注文促し 見守り',
        condition: '',
      },
      {
        order: 9,
        timing: '13:45',
        instruction: 'スケジュール確認',
        staff: '',
        activityDetail: '発表時は室内（第1作業室にいる）',
        instructionDetail: '室内（第一作業室にいてもらうようにする。） 見守り',
        condition: '',
      },
      {
        order: 10,
        timing: '13:45〜14:30',
        instruction: 'PM日中活動',
        staff: '',
        activityDetail: '第二作業室で本や小道具でリラックス 室内や廊下を歩く',
        instructionDetail: '活動準備 トイレ誘導・介助 見守り',
        condition: '',
      },
      {
        order: 11,
        timing: '14:30〜14:45',
        instruction: 'お茶休憩',
        staff: '',
        activityDetail: '手洗い、消毒後お茶を飲む',
        instructionDetail: '状況に応じて、手洗い、消毒、お茶を飲む補助又は介助',
        condition: '',
      },
      {
        order: 12,
        timing: '14:45〜15:20',
        instruction: 'PM日中活動',
        staff: '',
        activityDetail: '第二作業室で本や小道具でリラックス 室内や廊下を歩く',
        instructionDetail: '活動準備、片づけ トイレ誘導・介助 見守り',
        condition: '',
      },
      {
        order: 13,
        timing: '15:20〜15:40',
        instruction: 'のんびりタイム',
        staff: '',
        activityDetail: '自分のペースで自由に過ごす',
        instructionDetail: '状況に応じて、補助又は介助 見守り',
        condition: '',
      },
      {
        order: 14,
        timing: '15:40〜16:00',
        instruction: '帰りの準備',
        staff: '',
        activityDetail: '帰りの準備 室内にいる',
        instructionDetail: 'トイレ誘導・介助 帰りの準備補助又は介助 見守り',
        condition: '',
      },
      {
        order: 15,
        timing: '16:00',
        instruction: '退所',
        staff: '',
        activityDetail: '送迎車に乗る',
        instructionDetail: '送迎ボードを確認しながら送迎車を確認。安全に送迎車に乗れるよう付き添い介助',
        condition: '',
      },
      {
        order: 16,
        timing: '10:20/13:45〜10:25/13:50',
        instruction: 'AM PM日中活動（外活動準備）',
        staff: '',
        activityDetail: '出発前のトイレ',
        instructionDetail: 'トイレの介助 着替えを持つ 自動ドアの前で写真を撮る',
        condition: '',
      },
      {
        order: 17,
        timing: '10:25/13:50〜12:00/15:40',
        instruction: 'AM PM日中活動（外活動）',
        staff: '',
        activityDetail: '出発前のトイレ',
        instructionDetail: 'トイレの介助 着替えを持つ 自動ドアの前で写真を撮る',
        condition: '',
      },
    ],
    supportPriorities: [],
    antecedentStrategies: [],
    teachingStrategies: [],
    consequenceStrategies: [],
    crisisThresholds: null,
    restraintPolicy: 'prohibited_except_emergency',
    reviewCycleDays: 180, evaluationIndicator: "", evaluationPeriod: "", evaluationMethod: "", improvementResult: "", nextSupport: "",
    monitoringEvidenceLinks: [],
  },
  status: 'active',
  isCurrent: true,
  authoredByStaffId: 'staff-watanabe',
  applicableServiceType: 'other',
  applicableAddOnTypes: ['severe_disability_support'],
  monitoringCycleDays: 90,
  regulatoryBasisSnapshot: {
    supportLevel: 4,
    behaviorScore: 15,
    serviceType: '生活介護',
    eligibilityCheckedAt: '2026-04-01',
  },
  intake: {
    presentingProblem: '',
    targetBehaviorsDraft: [],
    behaviorItemsTotal: 15,
    incidentSummaryLast30d: '',
    communicationModes: ['本人のペース'],
    sensoryTriggers: [],
    medicalFlags: [],
    consentScope: [],
    consentDate: '2026-04-01',
  },
  assessment: {
    targetBehaviors: [],
    abcEvents: [],
    hypotheses: [],
    riskLevel: 'medium',
    healthFactors: [],
    teamConsensusNote: '',
  },
  reviewedAt: '2026-04-10',
  supportStartDate: '2026-04-01',
  deliveredToUserAt: '2026-04-05',
  authoredByQualification: 'practical_training',
  hasMedicalCoordination: false,
  hasEducationCoordination: false,
  authoredAt: '2026-04-10',
  appliedFrom: '2026-04-01',
  nextReviewAt: '2026-09-30', evaluationIndicator: "", evaluationPeriod: "", evaluationMethod: "", improvementResult: "", nextSupport: "",
  monitoringEvidenceLinks: [],
  createdAt: '2026-05-01T00:00:00Z',
  updatedAt: '2026-05-01T00:00:00Z',
  createdBy: 'staff-watanabe',
  updatedBy: 'staff-watanabe',
};
