import type { SupportPlanningSheet } from '@/domain/isp/schema/ispPlanningSheetSchema';

/**
 * 桂川 進太朗さんの「重度加算（外出入り）」の17行構成データ
 * 17行標準手順モデルの実務適合性検証用フィクスチャ
 */
export const KATSURAGAWA_SEVERE_SUPPORT_SHEET: SupportPlanningSheet = {
  id: 'katsuragawa-severe-sheet',
  userId: 'U-001',
  ispId: 'isp-katsuragawa-001',
  title: '桂川 進太朗 支援手順書（重度加算対応）',
  version: 1,
  targetScene: '日中活動',
  targetDomain: '生活全般',
  supportPolicy: '本人のペースを尊重し、見通しを持てるように視覚的支援を行う。',
  environmentalAdjustments: '視覚的スケジュールの提示、イヤーマフの活用。',
  concreteApproaches: '短い言葉で具体的に伝える。',
  observationFacts: '手持ち無沙汰の時に指の皮むきをしてしまう事がある。',
  interpretationHypothesis: '空き時間への不安や退屈が原因と考えられる。',
  supportIssues: '見通しを持てるように視覚的支援を行い、自律的な活動を促す。',
  collectedInformation: '家族・ヘルパーからの聞き取り。',
  planning: {
    procedureSteps: [
      {
        order: 1,
        timing: '通所',
        instruction: '通所 朝の準備',
        staff: '',
        activityDetail: '朝の準備 手洗い 荷物をロッカーへ 提出物を職員へ ハンカチ確認',
        instructionDetail: '通所時のヘルパーと申し送りをする。 手洗いの声掛け。 本人と朝の準備のお手伝い。 ハンカチ確認。',
        condition: '',
      },
      {
        order: 2,
        timing: '体操',
        instruction: '体操',
        staff: '',
        activityDetail: 'ラジオ体操をする',
        instructionDetail: '体操の声掛けをする。',
        condition: '',
      },
      {
        order: 3,
        timing: 'AM',
        instruction: 'スケジュール確認',
        staff: '',
        activityDetail: 'ホワイトボードを見ながら確認する',
        instructionDetail: 'ホワイトボードを使って声掛けし説明する。',
        condition: '',
      },
      {
        order: 4,
        timing: 'AM',
        instruction: 'お茶休憩',
        staff: '',
        activityDetail: '手洗いしお茶を飲む',
        instructionDetail: '手洗い・消毒の補助。 お茶を飲む・片付けるお手伝いをする。',
        condition: '',
      },
      {
        order: 5,
        timing: 'AM',
        instruction: 'AM日中活動',
        staff: '',
        activityDetail: '日中活動準備 ビン入れ ビーズの種類分け',
        instructionDetail: '座る場所の促しや準備のお手伝い。 活動の見守り・声掛けをする。',
        condition: '',
      },
      {
        order: 6,
        timing: '昼食',
        instruction: '昼食準備',
        staff: '',
        activityDetail: '手洗い・消毒・昼食の準備',
        instructionDetail: '手洗い等の声掛けや準備のお手伝いをする。',
        condition: '',
      },
      {
        order: 7,
        timing: '昼食',
        instruction: '昼食',
        staff: '',
        activityDetail: '食事の受け取り・食事 一部介助・片づけ・歯磨き',
        instructionDetail: '食事の受取や片付け、食事一部介助、食後の歯磨き介助などのお手伝いをする。',
        condition: '',
      },
      {
        order: 8,
        timing: 'PM',
        instruction: '昼休み',
        staff: '',
        activityDetail: '休み時間ののんびりタイム 血圧測定',
        instructionDetail: '静かな部屋への促しをする。 トイレの声掛け・介助。 血圧測定。',
        condition: '',
      },
      {
        order: 9,
        timing: 'PM',
        instruction: 'スケジュール確認',
        staff: '',
        activityDetail: 'ホワイトボードを見ながら確認する',
        instructionDetail: 'ホワイトボードを使って声掛けし説明する。',
        condition: '',
      },
      {
        order: 10,
        timing: 'PM',
        instruction: 'PM日中活動',
        staff: '',
        activityDetail: '日中活動準備 ビン入れ ビーズの種類分け',
        instructionDetail: '座る場所の促しや準備のお手伝い。 活動の見守り・声掛けをする。',
        condition: '',
      },
      {
        order: 11,
        timing: 'PM',
        instruction: 'お茶休憩',
        staff: '',
        activityDetail: '手洗いしお茶を飲む',
        instructionDetail: '手洗い・消毒の補助。 お茶を飲む・片付けるお手伝いをする。',
        condition: '',
      },
      {
        order: 12,
        timing: 'PM',
        instruction: 'PM日中活動',
        staff: '',
        activityDetail: '日中活動準備 ビン入れ ビーズの種類分け',
        instructionDetail: '座る場所の促しや準備のお手伝い。 活動の見守り・声掛けをする。',
        condition: '',
      },
      {
        order: 13,
        timing: 'PM',
        instruction: 'のんびりタイム',
        staff: '',
        activityDetail: 'のんびり過ごす',
        instructionDetail: 'のんびりできているかの確認。 座る場所の促しをする。 トイレの声掛け・介助。',
        condition: '',
      },
      {
        order: 14,
        timing: '退所',
        instruction: '帰りの準備',
        staff: '',
        activityDetail: '帰りの準備 荷物をロッカーから出す・着替え・トイレ、ハンカチ確認',
        instructionDetail: '荷物をロッカーから出す・着替え・ハンカチ確認・ノート返却などのお手伝いをする。',
        condition: '',
      },
      {
        order: 15,
        timing: '退所',
        instruction: '退所',
        staff: '',
        activityDetail: 'ヘルパーと一緒に帰る (木曜日は母)',
        instructionDetail: 'ヘルパーに引き継ぎ (木曜日は母) ご本人の様子を伝える。',
        condition: '',
      },
      {
        order: 16,
        timing: '外出',
        instruction: 'AM PM日中活動 (外活動準備)',
        staff: '',
        activityDetail: '着替えを持つ トイレに行く',
        instructionDetail: 'トイレの声掛け介助。 荷物の確認をする。 自動ドア前で写真を撮る休。',
        condition: '',
      },
      {
        order: 17,
        timing: '外出',
        instruction: 'AM PM日中活動 (外活動)',
        staff: '',
        activityDetail: '',
        instructionDetail: '',
        condition: '',
      },
    ],
    supportPriorities: [],
    antecedentStrategies: [],
    teachingStrategies: [],
    consequenceStrategies: [],
    crisisThresholds: null,
    restraintPolicy: 'prohibited_except_emergency',
    reviewCycleDays: 180, evaluationIndicator: "", evaluationPeriod: "", evaluationMethod: "", improvementResult: "", nextSupport: "",
    monitoringEvidenceLinks: [],
  },

  status: 'active',
  isCurrent: true,
  authoredByStaffId: 'staff-watanabe',
  applicableServiceType: 'other',
  applicableAddOnTypes: ['severe_disability_support'],
  monitoringCycleDays: 90,
  regulatoryBasisSnapshot: {
    supportLevel: 4,
    behaviorScore: 15,
    serviceType: '生活介護',
    eligibilityCheckedAt: '2026-04-01',
  },
  intake: {
    presentingProblem: '',
    targetBehaviorsDraft: [],
    behaviorItemsTotal: 15,
    incidentSummaryLast30d: '',
    communicationModes: ['写真カード'],
    sensoryTriggers: ['大きな音'],
    medicalFlags: [],
    consentScope: [],
    consentDate: '2026-04-01',
  },
  assessment: {
    targetBehaviors: [],
    abcEvents: [],
    hypotheses: [],
    riskLevel: 'medium',
    healthFactors: [],
    teamConsensusNote: '',
  },
  reviewedAt: '2026-04-10',
  supportStartDate: '2026-04-01',
  deliveredToUserAt: '2026-04-05',
  authoredByQualification: 'practical_training',
  hasMedicalCoordination: false,
  hasEducationCoordination: false,
  authoredAt: '2026-04-10',
  appliedFrom: '2026-04-01',
  nextReviewAt: '2026-09-30', evaluationIndicator: "", evaluationPeriod: "", evaluationMethod: "", improvementResult: "", nextSupport: "",
  monitoringEvidenceLinks: [],
  createdAt: '2026-05-01T00:00:00Z',
  updatedAt: '2026-05-01T00:00:00Z',
  createdBy: 'staff-watanabe',
  updatedBy: 'staff-watanabe',
};
