import type { SupportPlanningSheet } from '@/domain/isp/schema/ispPlanningSheetSchema';

/**
 * 中村 裕樹さんの「重度加算・外出入り」対応支援計画シート（17行モデル検証用）
 *
 * 特徴:
 * - 17行すべての手順ステップ (procedureSteps) を持つ
 * - RowNo 1〜15 (通常日課) + 16〜17 (外活動)
 * - 時間帯 (timing): 9:20頃 始まり（塩田さんの 9:40 / 桂川さんの 9:30 と異なる）
 * - RowNo 13 に「のんびりタイム」（動画鑑賞中心）
 * - 昼休みに財布管理やコーヒー等の声掛けが必要
 * - プレイルーム、和室、給食室への進入防止に注意
 * - 外活動 (16, 17) で出発前のトイレ確認・自動ドア前の写真撮影を含む
 */
export const NAKAMURA_SEVERE_SUPPORT_SHEET: SupportPlanningSheet = {
  id: 'sheet-nakamura-001',
  userId: 'I017',
  ispId: 'isp-nakamura-2026',
  title: '2026年度 個別支援計画（中村裕樹）',
  supportPolicy: '見通しを持ち、安心して活動に取り組む。制限エリアへの進入防止と自主課題の充実。',
  environmentalAdjustments: 'スケジュール表の提示。制限エリア（プレイルーム・和室・給食室）の視覚的表示。',
  concreteApproaches: '写真カードによる活動の提示。トイレ間隔の把握と声掛けのタイミング調整。',
  observationFacts: 'かさぶた・ささくれ・靴下の糸を気にする。ダイア磯子前の車を気にする。',
  interpretationHypothesis: '活動の見通しとルーティンの安定が行動の安定につながる。',
  supportIssues: '制限エリアへの進入防止。トイレ間隔の把握。かさぶた等への対処。',
  status: 'active',
  isCurrent: true,
  authoredByStaffId: 'staff-watanabe',
  authoredByQualification: 'practical_training',
  applicableServiceType: 'other',
  applicableAddOnTypes: ['severe_disability_support'],
  monitoringCycleDays: 90,
  regulatoryBasisSnapshot: {
    supportLevel: 4,
    behaviorScore: 15,
    serviceType: '生活介護',
    eligibilityCheckedAt: '2026-04-01',
  },
  intake: {
    presentingProblem: '',
    targetBehaviorsDraft: [],
    behaviorItemsTotal: 15,
    incidentSummaryLast30d: '',
    communicationModes: ['写真カード'],
    sensoryTriggers: ['かさぶた', 'ささくれ', '靴下の糸'],
    medicalFlags: [],
    consentScope: [],
    consentDate: '2026-04-01',
  },
  assessment: {
    targetBehaviors: [],
    abcEvents: [],
    hypotheses: [],
    riskLevel: 'medium',
    healthFactors: [],
    teamConsensusNote: '',
  },
  planning: {
    procedureSteps: [
      {
        order: 1,
        timing: '09:20頃',
        instruction: '通所・朝の準備',
        staff: '家族との引継ぎ、朝の準備支援',
        activityDetail: '家族の送迎で来所。車見送り。手洗い、各所確認。',
        instructionDetail: '家族との引継ぎを行い、手洗い・着替え等の朝の準備を支援する。',
        condition: '',
      },
      {
        order: 2,
        timing: '10:00頃',
        instruction: '体操',
        staff: '見守り、付き添い',
        activityDetail: 'ラジオ体操動画の確認',
        instructionDetail: '見守り。入ってはいけない場所へ行った際、付き添い。',
      },
      {
        order: 3,
        timing: '10:10頃',
        instruction: 'スケジュール確認',
        staff: '見守り',
        activityDetail: '活動内容発表時は室内（第１作業室）にいる',
        instructionDetail: '室内（第１作業室）にいてもらうようにする。見守り。',
      },
      {
        order: 4,
        timing: '10:15頃',
        instruction: 'お茶休憩',
        staff: '手洗い促し、誘導',
        activityDetail: '手洗い後、お茶を飲む',
        instructionDetail: '手洗い、消毒を促す。お茶の列に誘導する。',
      },
      {
        order: 5,
        timing: '10:20〜12:00',
        instruction: 'AM日中活動',
        staff: '活動準備、見守り',
        activityDetail: 'タオル作業（ペン入れ、鈴入れ）',
        instructionDetail: '活動準備の手伝い。タオル運び、見守り。',
      },
      {
        order: 6,
        timing: '12:00',
        instruction: '昼食準備',
        staff: '手洗い促し、見守り',
        activityDetail: '手洗い、消毒。昼食まで座っている。',
        instructionDetail: '手洗い、消毒を促す。席についている見守り。',
      },
      {
        order: 7,
        timing: '12:10〜12:40',
        instruction: '昼食',
        staff: '一部食事介助、見守り',
        activityDetail: '食事の受け取り。食後の片付け、手洗い。',
        instructionDetail: '一部食事介助、見守り。食後片付けの補助。',
      },
      {
        order: 8,
        timing: '12:40〜13:45',
        instruction: '昼休み',
        staff: 'タブレット順番管理、声掛け',
        activityDetail: '動画鑑賞。コーヒー等を飲む。寝て過ごす。',
        instructionDetail: 'タブレットの順番管理、声掛け。財布の声掛け、お金を出すところの見守り。',
      },
      {
        order: 9,
        timing: '13:45',
        instruction: 'スケジュール確認',
        staff: '見守り',
        activityDetail: '活動内容発表時は室内（第１作業室）にいる',
        instructionDetail: '室内（第１作業室）にいてもらうようにする。見守り。',
      },
      {
        order: 10,
        timing: '13:45〜14:30',
        instruction: 'PM日中活動',
        staff: '活動準備、見守り',
        activityDetail: 'ペン入れ、鈴入れ。自主課題。',
        instructionDetail: '活動準備の手伝い、見守り。',
      },
      {
        order: 11,
        timing: '14:30〜14:45',
        instruction: 'お茶休憩',
        staff: '手洗い促し、誘導',
        activityDetail: '手洗い後、お茶を飲む',
        instructionDetail: '手洗い、消毒を促す。お茶の列に誘導する。',
      },
      {
        order: 12,
        timing: '14:45〜15:20',
        instruction: 'PM日中活動',
        staff: '活動準備、見守り',
        activityDetail: 'ペン入れ、鈴入れ。自主課題。',
        instructionDetail: '活動準備の手伝い、見守り。',
      },
      {
        order: 13,
        timing: '15:20〜15:40',
        instruction: 'のんびりタイム',
        staff: '見守り、付き添い',
        activityDetail: '動画の確認、動画鑑賞。ご本人のペースで自由に過ごす。',
        instructionDetail: '入ってはいけない場所へ行った際付き添い、見守り。',
      },
      {
        order: 14,
        timing: '15:40〜16:00',
        instruction: '帰りの準備',
        staff: '着替え支援、付き添い',
        activityDetail: '着替え、帰りの準備。毛布干し。トイレ誘導。',
        instructionDetail: '着替え、帰りの準備の手伝い。ルーティンの付き添い。トイレの声掛け。',
      },
      {
        order: 15,
        timing: '16:00',
        instruction: '退所',
        staff: '送迎確認、付き添い',
        activityDetail: '送迎車に乗る',
        instructionDetail: '送迎ボードを確認しながら送迎車を確認。安全に送迎車に乗れるよう付き添い。',
      },
      {
        order: 16,
        timing: '10:20/13:45〜',
        instruction: '外活動準備',
        staff: 'トイレ声掛け、写真撮影',
        activityDetail: '出発前にトイレを確認する',
        instructionDetail: 'トイレの声掛け。自動ドア前で写真を撮る。',
      },
      {
        order: 17,
        timing: '10:25/13:50〜',
        instruction: '外活動',
        staff: 'トイレ声掛け、写真撮影',
        activityDetail: '出発前にトイレを確認する',
        instructionDetail: 'トイレの声掛け。自動ドア前で写真を撮る。',
      },
    ],
    supportPriorities: [],
    antecedentStrategies: [],
    teachingStrategies: [],
    consequenceStrategies: [],
    crisisThresholds: null,
    restraintPolicy: 'prohibited_except_emergency',
    reviewCycleDays: 180, evaluationIndicator: "", evaluationPeriod: "", evaluationMethod: "", improvementResult: "", nextSupport: "",
  },
  version: 1,
  targetScene: '日中活動',
  targetDomain: '生活介護',
  collectedInformation: '家族からの聞き取り。前年度の計画書。',
  supportStartDate: '2026-04-01',
  deliveredToUserAt: '2026-04-05',
  reviewedAt: '2026-04-10',
  hasMedicalCoordination: false,
  hasEducationCoordination: false,
  authoredAt: '2026-04-10',
  appliedFrom: '2026-04-01',
  nextReviewAt: '2026-09-30', evaluationIndicator: "", evaluationPeriod: "", evaluationMethod: "", improvementResult: "", nextSupport: "",
  createdAt: '2026-05-01T00:00:00Z',
  updatedAt: '2026-05-01T00:00:00Z',
  createdBy: 'staff-watanabe',
  updatedBy: 'staff-watanabe',
};
