// ---- Single source of truth for data-testid ----

// 値は常に文字列。キーと同じ値を返すことでテストコードからの参照を簡易化。
export const TESTIDS = {
  // Shell / Router
  'app-root': 'app-root',
  'app-router-outlet': 'app-router-outlet',

  // Pages
  'meeting-guide': 'meeting-guide',
  'meeting-guide-page': 'meeting-guide-page',
  'dashboard-page': 'dashboard-page',
  'dashboard-records': 'dashboard-records',
  'attendance-page': 'attendance-page',
  'plan-create-page': 'plan-create-page',
  'plan-edit-page': 'plan-edit-page',
  'profile-placeholder': 'profile-placeholder',

  // Features
  'record-form': 'record-form',
  'record-table': 'record-table',
  'record-row': 'record-row',
  'toast-announcer': 'toast-announcer',
  'toast-message': 'toast-message',
  'nav-schedules': 'nav-schedules',
  'app-bottom-nav': 'app-bottom-nav',
  'support-incident-dialog': 'support-incident-dialog',
  'support-incident-stepper': 'support-incident-stepper',
  'support-incident-submit': 'support-incident-submit',

  // Nurse UI slice
  NURSE_NAV_HOME: 'nurse.nav.home',
  NURSE_NAV_OBS: 'nurse.nav.observation',
  NURSE_NAV_BULK: 'nurse.nav.bulk',
  NURSE_NAV_MEDS: 'nurse.nav.medication',
  NURSE_HOME_PAGE: 'nurse.page.home',
  NURSE_HOME_TASK_ITEM: 'nurse.home.task',
  NURSE_OBS_PAGE: 'nurse.page.observation',
  NURSE_BULK_PAGE: 'nurse.page.bulk',
  NURSE_MEDS_PAGE: 'nurse.page.medication',
  NURSE_RECORDS_PAGE: 'nurse.page.records',
  NURSE_OBS_USER: 'nurse.obs.user',
  NURSE_OBS_MEMO: 'nurse.obs.memo',
  NURSE_OBS_SAVE: 'nurse.obs.save',
  NURSE_OBS_HEADING: 'nurse.obs.heading',
  NURSE_OBS_FORM_SECTION: 'nurse.obs.form.section',
  NURSE_MEDS_SAVE: 'nurse.meds.save',
  NURSE_MEDS_GRID_SUMMARY: 'nurse.meds.grid.summary',
  NURSE_MEDS_GRID_CONTROLS: 'nurse.meds.grid.controls',
  NURSE_SYNC_BUTTON: 'nurse.sync.button',
  NURSE_SYNC_STATUS: 'nurse.sync.status',
  NURSE_RECORDS_SEARCH: 'nurse.records.search',
  NURSE_RECORDS_REGION: 'nurse.records.region',
  NURSE_RECORDS_HEADING: 'nurse.records.heading',
  NURSE_USER_LIST: 'nurse.user.list',
  NURSE_USER_ITEM: 'nurse.user.item',
  NURSE_OBS_WEIGHT_CARD: 'nurse-obs-weight-card',
  NURSE_OBS_WEIGHT_INPUT: 'nurse-obs-weight-input',
  NURSE_MEMO_TOGGLE: 'nurse-memo-toggle',
  NURSE_MEMO_PANEL: 'nurse-memo-panel',
  NURSE_ACTION_BAR: 'nurse-action-bar',
  NURSE_VITAL_VALUE: 'nurse-vital-value',
  NURSE_TABS: 'nurse-tabs',
  NURSE_TAB_OBSERVE: 'nurse-tab-observe',
  NURSE_TAB_SEIZURE: 'nurse-tab-seizure',
  NURSE_TAB_BP: 'nurse-tab-bp',
  NURSE_TAB_RECORDS: 'nurse-tab-records',
  NURSE_SEIZURE_PANEL: 'nurse-seizure-panel',
  NURSE_SEIZURE_RECORD_BUTTON: 'nurse-seizure-record-button',
  NURSE_SEIZURE_QUICKLOG: 'NURSE_SEIZURE_QUICKLOG',
  NURSE_SEIZURE_LOG_LIST: 'nurse-seizure-log-list',
  NURSE_SEIZURE_EMPTY: 'nurse-seizure-empty',
  NURSE_SEIZURE_DATE: 'nurse-seizure-date',
  NURSE_BULK_TABLE: 'nurse-bulk-table',
  NURSE_BULK_SYNC: 'nurse-bulk-sync',
  NURSE_BULK_ROW_PREFIX: 'nurse-bulk-row',
  NURSE_BULK_SAVE_PREFIX: 'nurse-bulk-save',
  NURSE_BULK_STATUS_PREFIX: 'nurse-bulk-status',
  NURSE_BULK_FIELD_PREFIX: 'nurse-bulk',
  NURSE_BULK_FILTER_GROUP: 'nurse-bulk-filter-group',
  NURSE_BULK_FILTER_ALL: 'nurse-bulk-filter-all',
  NURSE_BULK_FILTER_THU: 'nurse-bulk-filter-thu',
  NURSE_BULK_FILTER_FRI: 'nurse-bulk-filter-fri',
  NURSE_BULK_SHORTCUT_HINT: 'nurse-bulk-shortcut-hint',
  NURSE_BULK_STATUS_LEGEND: 'nurse-bulk-status-legend',
  NURSE_BULK_DATE: 'nurse-bulk-date',
  NURSE_BULK_TO_INDIVIDUAL: 'nurse-bulk-to-individual',
  NURSE_BULK_COL_USER: 'nurse-bulk-col-user',
  NURSE_BULK_COL_TEMP: 'nurse-bulk-col-temp',
  NURSE_BULK_COL_WEIGHT: 'nurse-bulk-col-weight',
  NURSE_BULK_COL_MEMO: 'nurse-bulk-col-memo',
  NURSE_BULK_COL_SAVE: 'nurse-bulk-col-save',
  NURSE_BULK_COL_STATUS: 'nurse-bulk-col-status',
  NURSE_BP_INPUT_PULSE: 'nurse-bp-input-pulse',
  NURSE_BP_INPUT_SYS: 'nurse-bp-input-sys',
  NURSE_BP_INPUT_DIA: 'nurse-bp-input-dia',
  NURSE_BP_SAVE: 'nurse-bp-save',
  NURSE_BP_PANEL: 'nurse-bp-panel',
  NURSE_BP_LAST_SAVED: 'nurse-bp-last-saved',
  NURSE_BP_QUEUE: 'nurse-bp-queue',
  NURSE_SYNC_ANNOUNCE: 'NURSE_SYNC_ANNOUNCE',
  NURSE_SYNC_ANNOUNCE_VISIBLE: 'NURSE_SYNC_ANNOUNCE_VISIBLE',
  NURSE_SYNC_TOAST: 'nurse-sync-toast',
  NURSE_TOAST_RETRY: 'NURSE_TOAST_RETRY',
  NURSE_SYNC_HUD: 'NURSE_SYNC_HUD',
  NURSE_SYNC_MINUTE_LABEL: 'NURSE_SYNC_MINUTE_LABEL',
  NURSE_NUMERIC_DIALOG: 'nurse.numeric.dialog',
  NURSE_NUMERIC_KEY: 'nurse.numeric.key',
  NURSE_NUMERIC_CLEAR: 'nurse.numeric.clear',
  NURSE_NUMERIC_BACKSPACE: 'nurse.numeric.backspace',

  // Users feature
  'users-panel-root': 'users-panel-root',
  'users-list-table': 'users-list-table',
  'users-detail-pane': 'users-detail-pane',
  'user-detail-sections': 'user-detail-sections',
  'users-quick-prefix': 'users-quick-',
  'user-menu-card-prefix': 'user-menu-card-',
  'user-menu-tabpanel-prefix': 'user-menu-tabpanel-',
    // User Menu関連
  'user-menu-trigger': 'user-menu-trigger',
  'user-menu-popup': 'user-menu-popup',
  'user-menu-profile-item': 'user-menu-profile-item',
  'user-menu-features-item': 'user-menu-features-item',
  'user-menu-signout-item': 'user-menu-signout-item',
  'user-menu-section-prefix': 'user-menu-section-',

  // Monthly Records関連
  'monthly-page': 'monthly-page',
  'monthly-tab-summary': 'monthly-tab-summary',
  'monthly-tab-detail': 'monthly-tab-detail',
  'monthly-tab-pdf': 'monthly-tab-pdf',
  'monthly-summary-table': 'monthly-summary-table',
  'monthly-summary-search': 'monthly-summary-search',
  'monthly-summary-month-select': 'monthly-summary-month-select',
  'monthly-summary-rate-filter': 'monthly-summary-rate-filter',
  'monthly-summary-reaggregate-btn': 'monthly-summary-reaggregate-btn',
  'monthly-summary-status': 'monthly-summary-status',
  'monthly-detail-user-select': 'monthly-detail-user-select',
  'monthly-detail-month-select': 'monthly-detail-month-select',
  'monthly-detail-records-table': 'monthly-detail-records-table',
  'monthly-pdf-generate-btn': 'monthly-pdf-generate-btn',
} as const;



// React で使うお手軽ヘルパー（型はstringで十分）
export function tid(id: string) {
  return { 'data-testid': id } as const;
}
