// ---- Single source of truth for data-testid ----

// 値は常に文字列。テストコードからは TESTIDS.xxx を経由して参照する（文字列リテラルは直書きしない）。
const NAV_TESTIDS = {
  dashboard: 'nav-dashboard',
  analysis: 'nav-analysis',
  iceberg: 'nav-iceberg',
  icebergPdca: 'nav-iceberg-pdca',
  assessment: 'nav-assessment',
  daily: 'nav-daily',
  checklist: 'nav-checklist',
  audit: 'nav-audit',
  admin: 'nav-admin',
  schedules: 'nav-schedules',
  staffAttendance: 'nav-staff-attendance',
  nurse: 'nav-nurse',
  supportPlanGuide: 'nav-support-plan-guide',
} as const;

const FOOTER_TESTIDS = {
  dailyAttendance: 'footer-action-daily-attendance',
  dailyActivity: 'footer-action-daily-activity',
  // New canonical footer ids (2024+)
  dailyFooterAttendance: 'daily-footer-attendance',
  dailyFooterActivity: 'daily-footer-activity',
  schedulesFooterMonth: 'schedules-footer-month',
} as const;

export const TESTIDS = {
  // Shell / Router
  'app-root': 'app-root',
  'app-router-outlet': 'app-router-outlet',
  'nav-open': 'nav-open',
  'sp-connection-status': 'sp-connection-status',

  // Pages
  'meeting-guide': 'meeting-guide',
  'meeting-guide-page': 'meeting-guide-page',
  'dashboard-page': 'dashboard-page',
  'dashboard-page-tabs': 'dashboard-page-tabs', // 🧪 黒ノート機能タブ専用（日次ダッシュボードと区別）
  'dashboard-records': 'dashboard-records',
  'audit-heading': 'audit-heading',
  'iceberg-pdca-root': 'iceberg-pdca-root',
  'iceberg-pdca-empty': 'iceberg-pdca-empty',
  'pdca-daily-completion-card': 'pdca-daily-completion-card',
  'pdca-daily-completion-value': 'pdca-daily-completion-value',
  'pdca-daily-leadtime-card': 'pdca-daily-leadtime-card',
  'pdca-daily-leadtime-value': 'pdca-daily-leadtime-value',
  'pdca-daily-trend-card': 'pdca-daily-trend-card',
  'pdca-trend-period-toggle': 'pdca-trend-period-toggle',
  'pdca-trend-period-weekly': 'pdca-trend-period-weekly',
  'pdca-trend-period-monthly': 'pdca-trend-period-monthly',
  'pdca-weekly-completion-trend': 'pdca-weekly-completion-trend',
  'pdca-monthly-completion-trend': 'pdca-monthly-completion-trend',
  'pdca-weekly-leadtime-trend': 'pdca-weekly-leadtime-trend',
  'pdca-monthly-leadtime-trend': 'pdca-monthly-leadtime-trend',
  ICEBERG_PDCA_EMPTY: 'iceberg-pdca-empty',

  // Dashboard Tabs (黒ノート機能個別タブ) 🌱 E2Eでタブ切替を細かく検査用
  'dashboard-tab-management': 'dashboard-tab-management',
  'dashboard-tab-timeline': 'dashboard-tab-timeline',
  'dashboard-tab-weekly': 'dashboard-tab-weekly',
  'dashboard-tab-meeting': 'dashboard-tab-meeting',
  'dashboard-tab-morning': 'dashboard-tab-morning',
  'dashboard-tab-evening': 'dashboard-tab-evening',
  'dashboard-tab-profile': 'dashboard-tab-profile',
  'attendance-page': 'attendance-page',
  'plan-create-page': 'plan-create-page',
  'plan-edit-page': 'plan-edit-page',
  'profile-placeholder': 'profile-placeholder',

  // Features
  'record-form': 'record-form',
  'record-table': 'record-table',
  'record-row': 'record-row',
  'toast-announcer': 'toast-announcer',
  'toast-message': 'toast-message',
  'handoff-footer-quicknote': 'handoff-footer-quicknote',
  ...NAV_TESTIDS,
  ...FOOTER_TESTIDS,
  nav: NAV_TESTIDS,
  footer: FOOTER_TESTIDS,
  // Legacy flat keys (compatibility with existing lookups)
  'nav-dashboard': 'nav-dashboard',
  'nav-analysis': 'nav-analysis',
  'nav-iceberg': 'nav-iceberg',
  'nav-iceberg-pdca': 'nav-iceberg-pdca',
  'nav-assessment': 'nav-assessment',
  'nav-daily': 'nav-daily',
  'nav-checklist': 'nav-checklist',
  'nav-audit': 'nav-audit',
  'nav-admin': 'nav-admin',
  'nav-schedules': 'nav-schedules',
  'nav-staff-attendance': 'nav-staff-attendance',
  'nav-nurse': 'nav-nurse',
  'footer-action-daily-attendance': 'footer-action-daily-attendance',
  'footer-action-daily-activity': 'footer-action-daily-activity',
  // Compatibility: new footer ids used by AppShell (2024+)
  'daily-footer-attendance': 'daily-footer-attendance',
  'daily-footer-activity': 'daily-footer-activity',
  'daily-footer-support': 'daily-footer-support',
  'daily-footer-health': 'daily-footer-health',
  'schedules-footer-month': 'schedules-footer-month',
  'handoff-footer-timeline': 'handoff-footer-timeline',
  'daily-table-record-page': 'daily-table-record-page',
  'daily-table-record-form': 'daily-table-record-form',
  'daily-table-record-form-user-list': 'daily-table-record-form-user-list',
  'daily-table-record-form-table': 'daily-table-record-form-table',
  'daily-table-draft-save': 'daily-table-draft-save',
  'daily-table-draft-status': 'daily-table-draft-status',
  'daily-table-unsent-filter': 'daily-table-unsent-filter',
  'daily-table-unsent-count-chip': 'daily-table-unsent-count-chip',
  'daily-table-support-hint-icon': 'daily-table-support-hint-icon',
  'daily-table-support-hint-text': 'daily-table-support-hint-text',
  'bulk-daily-record-form': 'bulk-daily-record-form',
  'bulk-daily-record-user-list': 'bulk-daily-record-user-list',
  'bulk-daily-record-user-row-prefix': 'bulk-daily-record-user-row-',
  'bulk-daily-record-search': 'bulk-daily-record-search',
  'bulk-daily-record-select-all': 'bulk-daily-record-select-all',
  'bulk-daily-record-clear-all': 'bulk-daily-record-clear-all',
  'bulk-daily-record-activity-input-am': 'bulk-daily-record-activity-input-am',
  'bulk-daily-record-activity-input-pm': 'bulk-daily-record-activity-input-pm',
  'bulk-daily-record-activity-chip-am': 'bulk-daily-record-activity-chip-am',
  'bulk-daily-record-activity-chip-pm': 'bulk-daily-record-activity-chip-pm',
  'bulk-daily-record-activity-delete-am': 'bulk-daily-record-activity-delete-am',
  'bulk-daily-record-activity-delete-pm': 'bulk-daily-record-activity-delete-pm',
  'bulk-daily-record-individual-notes': 'bulk-daily-record-individual-notes',
  'schedules-nav-link': 'schedules-nav-link',
  'home-tile-schedule': 'home-tile-schedule',
  'schedules-day-page': 'schedules-day-page',
  'schedules-day-heading': 'schedules-day-heading',
  'schedules-day-list': 'schedules-day-list',
  'schedules-day-skeleton': 'schedules-day-skeleton',
  'schedules-day-popover': 'schedules-day-popover',
  'schedules-popover-open-day': 'schedules-popover-open-day',
  SCHEDULES_PAGE_ROOT: 'schedules-page-root',
  'schedules-week-page': 'schedules-week-page',
  'schedules-week-heading': 'schedules-week-heading',
  'schedules-week-grid': 'schedules-week-grid',
  'schedule-week-root': 'schedule-week-root',
  SCHEDULE_WEEK_ROOT: 'schedule-week-root',
  'schedule-week-view': 'schedule-week-view',
  'schedules-week-view': 'schedules-week-view',
  SCHEDULE_WEEK_VIEW: 'schedule-week-view',
  SCHEDULES_WEEK_VIEW: 'schedules-week-view',
  SCHEDULES_WEEK_SERVICE_SUMMARY: 'schedules-week-service-summary',
  'schedule-week-list': 'schedule-week-list',
  SCHEDULE_WEEK_LIST: 'schedule-week-list',
  'schedule-week-empty': 'schedule-week-empty',
  SCHEDULE_WEEK_EMPTY: 'schedule-week-empty',
  // ✨ 新: ヘッダーのMUI Tabs統一後の命名
  SCHEDULES_WEEK_TABLIST: 'schedules-view-tabs',
  SCHEDULES_WEEK_TAB_WEEK: 'schedules-view-tab-week',
  SCHEDULES_WEEK_TAB_DAY: 'schedules-view-tab-day',
  SCHEDULES_WEEK_TAB_MONTH: 'schedules-view-tab-month',
  SCHEDULE_WEEK_ORG_INDICATOR: 'schedule-week-org-indicator',
  SCHEDULE_DAY_ORG_INDICATOR: 'schedule-day-org-indicator',
  SCHEDULE_MONTH_ORG_INDICATOR: 'schedule-month-org-indicator',
  SCHEDULES_HEADER_ROOT: 'schedules-header-root',
  SCHEDULES_HEADER_CREATE: 'schedules-header-create',
  SCHEDULES_RANGE_LABEL: 'schedules-range-label',
  SCHEDULES_EMPTY_HINT: 'schedules-empty-hint',
  SCHEDULES_FILTER_GROUP: 'schedules-filter-group',
  SCHEDULES_FILTER_TOGGLE: 'schedules-filter-toggle',
  SCHEDULES_FILTER_DIALOG: 'schedules-filter-dialog',
  'schedules-filter-category': 'schedules-filter-category',
  'schedules-filter-query': 'schedules-filter-query',
  SCHEDULES_WEEK_DAY_PREFIX: 'schedules-week-day',
  'schedules-empty': 'schedules-empty',
  'schedules-prev': 'schedules-prev',
  'schedules-next': 'schedules-next',
  SCHEDULES_PREV_WEEK: 'schedules-prev-week',
  SCHEDULES_NEXT_WEEK: 'schedules-next-week',
  SCHEDULES_FAB_CREATE: 'schedules-fab-create',
  'schedules-week-live': 'schedules-week-live',
  'schedule-item-menu': 'schedule-item-menu',
  SCHEDULES_MONTH_PAGE: 'schedules-month-page',
  SCHEDULES_MONTH_HEADING_ID: 'schedules-month-heading',
  SCHEDULES_MONTH_RANGE_ID: 'schedules-month-range',
  SCHEDULES_MONTH_PREV: 'schedules-month-prev',
  SCHEDULES_MONTH_NEXT: 'schedules-month-next',
  SCHEDULES_MONTH_DAY_PREFIX: 'schedules-month-day',
  'schedules-event-conflicted': 'schedules-event-conflicted',
  'schedules-event-normal': 'schedules-event-normal',
  'schedule-item': 'schedule-item',
  SCHEDULE_ITEM: 'schedule-item',
  'schedule-create-quick-button': 'schedule-create-quick-button',
  'schedule-create-dialog': 'schedule-create-dialog',
  'schedule-editor-root': 'schedule-editor-root',
  'schedule-create-heading': 'schedule-create-heading',
  'schedule-create-description': 'schedule-create-description',
  'schedule-create-error-alert': 'schedule-create-error-alert',
  'schedule-create-title': 'schedule-create-title',
  'schedule-create-user-input': 'schedule-create-user-input',
  'schedule-create-category-select': 'schedule-create-category-select',
  'schedule-create-start': 'schedule-create-start',
  'schedule-create-end': 'schedule-create-end',
  'schedule-create-service-type': 'schedule-create-service-type',
  'schedule-create-location': 'schedule-create-location',
  'schedule-create-notes': 'schedule-create-notes',
  'schedule-create-staff-id': 'schedule-create-staff-id',
  'schedule-create-vehicle-id': 'schedule-create-vehicle-id',
  'schedule-create-status': 'schedule-create-status',
  'schedule-create-save': 'schedule-create-save',
  'schedule-editor-save': 'schedule-editor-save',
  'dev-schedule-dialog-open': 'dev-schedule-dialog-open',
  'dev-schedule-dialog-page': 'dev-schedule-dialog-page',

  // Operations Dashboard
  'operations-dashboard-page': 'operations-dashboard-page',
  'operations-safety-hud': 'operations-safety-hud',
  'operations-safety-hud-total': 'operations-safety-hud-total',
  'operations-safety-hud-kind-list': 'operations-safety-hud-kind-list',
  'operations-staff-load-panel': 'operations-staff-load-panel',
  'operations-staff-load-row': 'operations-staff-load-row',
  'operations-vehicle-panel': 'operations-vehicle-panel',
  'operations-vehicle-row': 'operations-vehicle-row',

  // Daily Dashboard (Stage 9)
  'dashboard-safety-hud': 'dashboard-safety-hud',
  'dashboard-handoff-summary': 'dashboard-handoff-summary',
  'dashboard-handoff-summary-total': 'dashboard-handoff-summary-total',
  'dashboard-handoff-summary-alert': 'dashboard-handoff-summary-alert',
  'dashboard-handoff-summary-action': 'dashboard-handoff-summary-action',
  'dashboard-tabs': 'dashboard-tabs',
  'dashboard-briefing-page': 'dashboard-briefing-page',
  'dashboard-briefing-summary-morning': 'dashboard-briefing-summary-morning',
  'dashboard-briefing-summary-evening': 'dashboard-briefing-summary-evening',
  'dashboard-briefing-guide-morning': 'dashboard-briefing-guide-morning',
  'dashboard-briefing-guide-evening': 'dashboard-briefing-guide-evening',
  'tab-overview': 'tab-overview',
  'tab-morning': 'tab-morning',
  'tab-evening': 'tab-evening',
  'btn-morning-mode': 'btn-morning-mode',
  'btn-evening-mode': 'btn-evening-mode',
  'dashboard-daily-status-card-通所記録': 'dashboard-daily-status-card-通所記録',
  'dashboard-daily-status-card-日誌': 'dashboard-daily-status-card-日誌',
  'dashboard-daily-status-card-支援手順': 'dashboard-daily-status-card-支援手順',
  'module-summary-cards': 'module-summary-cards',
  'module-summary-card-activity': 'module-summary-card-activity',
  'module-summary-card-attendance': 'module-summary-card-attendance',
  'module-summary-card-irc': 'module-summary-card-irc',

  // Morning/Evening Meeting System
  'dashboard-briefing-panel': 'dashboard-briefing-panel',
  'briefing-safety-summary': 'briefing-safety-summary',
  'briefing-progress-summary': 'briefing-progress-summary',
  'briefing-priority-users': 'briefing-priority-users',
  'briefing-handoff-summary': 'briefing-handoff-summary',
  'dashboard-next-action-card': 'dashboard-next-action-card',
  'next-action-main-button': 'next-action-main-button',
  'meeting-progress-memo': 'meeting-progress-memo',
  'meeting-guide-morning': 'meeting-guide-morning',
  'meeting-guide-evening': 'meeting-guide-evening',
  'meeting-guide-checklist': 'meeting-guide-checklist',
  'meeting-guide-clear': 'meeting-guide-clear',

  'schedule-conflict-guide-dialog': 'schedule-conflict-guide-dialog',
  'schedule-conflict-guide-title': 'schedule-conflict-guide-title',
  'schedule-conflict-guide-content': 'schedule-conflict-guide-content',
  'schedule-conflict-guide-item': 'schedule-conflict-guide-item',
  'schedule-conflict-guide-actions': 'schedule-conflict-guide-actions',
  'schedule-conflict-guide-close': 'schedule-conflict-guide-close',
  'schedule-conflict-guide-apply-30min-later': 'schedule-conflict-guide-apply-30min-later',
  // ミニ時間提案エンジン用のテストID
  'schedule-conflict-guide-apply-30min-earlier': 'schedule-conflict-guide-apply-30min-earlier',
  'schedule-conflict-guide-apply-60min-later': 'schedule-conflict-guide-apply-60min-later',
  'schedule-conflict-guide-suggestion-buttons': 'schedule-conflict-guide-suggestion-buttons',
  // 職員代替案エンジン用のテストID
  'schedule-conflict-guide-staff-alternatives': 'schedule-conflict-guide-staff-alternatives',
  'schedule-conflict-guide-staff-alternative': 'schedule-conflict-guide-staff-alternative',
  'schedule-conflict-guide-apply-staff': 'schedule-conflict-guide-apply-staff',
  // 車両代替案エンジン用のテストID（Stage 7）
  'schedule-conflict-guide-vehicle-alternatives': 'schedule-conflict-guide-vehicle-alternatives',
  'schedule-conflict-guide-vehicle-alternative': 'schedule-conflict-guide-vehicle-alternative',
  'schedule-conflict-guide-apply-vehicle': 'schedule-conflict-guide-apply-vehicle',
  // 部屋代替案エンジン用のテストID（Stage 8）
  'schedule-conflict-guide-room-alternatives': 'schedule-conflict-guide-room-alternatives',
  'schedule-conflict-guide-room-alternative': 'schedule-conflict-guide-room-alternative',
  'schedule-conflict-guide-apply-room': 'schedule-conflict-guide-apply-room',
  // 設備代替案エンジン用のテストID（Stage 8）
  'schedule-conflict-guide-equipment-alternatives': 'schedule-conflict-guide-equipment-alternatives',
  'schedule-conflict-guide-equipment-alternative': 'schedule-conflict-guide-equipment-alternative',
  'schedule-conflict-guide-apply-equipment': 'schedule-conflict-guide-apply-equipment',
  'app-bottom-nav': 'app-bottom-nav',
  'support-incident-dialog': 'support-incident-dialog',
  'support-incident-stepper': 'support-incident-stepper',
  'support-incident-submit': 'support-incident-submit',

  // Nurse UI slice
  NURSE_NAV_HOME: 'nurse.nav.home',
  NURSE_NAV_OBS: 'nurse.nav.observation',
  NURSE_NAV_BULK: 'nurse.nav.bulk',
  NURSE_NAV_MEDS: 'nurse.nav.medication',
  NURSE_HOME_PAGE: 'nurse.page.home',
  'nurse-dashboard-root': 'nurse-dashboard-root',
  'nurse-dashboard-summary-total': 'nurse-dashboard-summary-total',
  'nurse-dashboard-summary-pending': 'nurse-dashboard-summary-pending',
  'nurse-dashboard-summary-in-progress': 'nurse-dashboard-summary-in-progress',
  'nurse-dashboard-summary-completed': 'nurse-dashboard-summary-completed',
  'nurse-dashboard-task-row': 'nurse-dashboard-task-row',
  NURSE_HOME_TASK_ITEM: 'nurse.home.task',
  NURSE_OBS_PAGE: 'nurse.page.observation',
  NURSE_BULK_PAGE: 'nurse.page.bulk',
  NURSE_MEDS_PAGE: 'nurse.page.medication',
  NURSE_RECORDS_PAGE: 'nurse.page.records',
  NURSE_OBS_USER: 'nurse.obs.user',
  NURSE_OBS_MEMO: 'nurse.obs.memo',
  NURSE_OBS_SAVE: 'nurse.obs.save',
  NURSE_OBS_HEADING: 'nurse.obs.heading',
  NURSE_OBS_FORM_SECTION: 'nurse.obs.form.section',
  NURSE_MEDS_SAVE: 'nurse.meds.save',
  NURSE_MEDS_GRID_SUMMARY: 'nurse.meds.grid.summary',
  NURSE_MEDS_GRID_CONTROLS: 'nurse.meds.grid.controls',
  NURSE_SYNC_BUTTON: 'nurse.sync.button',
  NURSE_SYNC_STATUS: 'nurse.sync.status',
  NURSE_RECORDS_SEARCH: 'nurse.records.search',
  NURSE_RECORDS_REGION: 'nurse.records.region',
  NURSE_RECORDS_HEADING: 'nurse.records.heading',
  NURSE_USER_LIST: 'nurse.user.list',
  NURSE_USER_ITEM: 'nurse.user.item',
  NURSE_OBS_WEIGHT_CARD: 'nurse-obs-weight-card',
  NURSE_OBS_WEIGHT_INPUT: 'nurse-obs-weight-input',
  NURSE_MEMO_TOGGLE: 'nurse-memo-toggle',
  NURSE_MEMO_PANEL: 'nurse-memo-panel',
  NURSE_ACTION_BAR: 'nurse-action-bar',
  NURSE_VITAL_VALUE: 'nurse-vital-value',
  NURSE_TABS: 'nurse-tabs',
  NURSE_TAB_OBSERVE: 'nurse-tab-observe',
  NURSE_TAB_SEIZURE: 'nurse-tab-seizure',
  NURSE_TAB_BP: 'nurse-tab-bp',
  NURSE_TAB_RECORDS: 'nurse-tab-records',
  NURSE_SEIZURE_PANEL: 'nurse-seizure-panel',
  NURSE_SEIZURE_RECORD_BUTTON: 'nurse-seizure-record-button',
  NURSE_SEIZURE_QUICKLOG: 'NURSE_SEIZURE_QUICKLOG',
  NURSE_SEIZURE_LOG_LIST: 'nurse-seizure-log-list',
  NURSE_SEIZURE_EMPTY: 'nurse-seizure-empty',
  NURSE_SEIZURE_DATE: 'nurse-seizure-date',
  NURSE_BULK_TABLE: 'nurse-bulk-table',
  NURSE_BULK_SYNC: 'nurse-bulk-sync',
  NURSE_BULK_ROW_PREFIX: 'nurse-bulk-row',
  NURSE_BULK_SAVE_PREFIX: 'nurse-bulk-save',
  NURSE_BULK_STATUS_PREFIX: 'nurse-bulk-status',
  NURSE_BULK_FIELD_PREFIX: 'nurse-bulk',
  NURSE_BULK_FILTER_GROUP: 'nurse-bulk-filter-group',
  NURSE_BULK_FILTER_ALL: 'nurse-bulk-filter-all',
  NURSE_BULK_FILTER_THU: 'nurse-bulk-filter-thu',
  NURSE_BULK_FILTER_FRI: 'nurse-bulk-filter-fri',
  NURSE_BULK_SHORTCUT_HINT: 'nurse-bulk-shortcut-hint',
  NURSE_BULK_STATUS_LEGEND: 'nurse-bulk-status-legend',
  NURSE_BULK_DATE: 'nurse-bulk-date',
  NURSE_BULK_TO_INDIVIDUAL: 'nurse-bulk-to-individual',
  NURSE_BULK_COL_USER: 'nurse-bulk-col-user',
  NURSE_BULK_COL_TEMP: 'nurse-bulk-col-temp',
  NURSE_BULK_COL_WEIGHT: 'nurse-bulk-col-weight',
  NURSE_BULK_COL_MEMO: 'nurse-bulk-col-memo',
  NURSE_BULK_COL_SAVE: 'nurse-bulk-col-save',
  NURSE_BULK_COL_STATUS: 'nurse-bulk-col-status',
  NURSE_BP_INPUT_PULSE: 'nurse-bp-input-pulse',
  NURSE_BP_INPUT_SYS: 'nurse-bp-input-sys',
  NURSE_BP_INPUT_DIA: 'nurse-bp-input-dia',
  NURSE_BP_SAVE: 'nurse-bp-save',
  NURSE_BP_PANEL: 'nurse-bp-panel',
  NURSE_BP_LAST_SAVED: 'nurse-bp-last-saved',
  NURSE_BP_QUEUE: 'nurse-bp-queue',
  NURSE_SYNC_ANNOUNCE: 'NURSE_SYNC_ANNOUNCE',
  NURSE_SYNC_ANNOUNCE_VISIBLE: 'NURSE_SYNC_ANNOUNCE_VISIBLE',
  NURSE_SYNC_TOAST: 'nurse-sync-toast',
  NURSE_TOAST_RETRY: 'NURSE_TOAST_RETRY',
  NURSE_SYNC_HUD: 'NURSE_SYNC_HUD',
  NURSE_SYNC_MINUTE_LABEL: 'NURSE_SYNC_MINUTE_LABEL',
  NURSE_NUMERIC_DIALOG: 'nurse.numeric.dialog',
  NURSE_NUMERIC_KEY: 'nurse.numeric.key',
  NURSE_NUMERIC_CLEAR: 'nurse.numeric.clear',
  NURSE_NUMERIC_BACKSPACE: 'nurse.numeric.backspace',

  // Users feature
  'users-panel-root': 'users-panel-root',
  'users-panel-open': 'users-panel-open',
  'users-panel-search': 'users-panel-search',
  'users-panel-filter-active': 'users-panel-filter-active',
  'users-panel-filter-severe': 'users-panel-filter-severe',
  'users-list-table': 'users-list-table',
  'users-list-table-row': 'users-list-table-row',
  'users-detail-pane': 'users-detail-pane',
  'user-detail-sections': 'user-detail-sections',
  'users-quick-prefix': 'users-quick-',
  'user-menu-card-prefix': 'user-menu-card-',
  'user-menu-tabpanel-prefix': 'user-menu-tabpanel-',

  // Staff feature
  'staff-panel-root': 'staff-panel-root',

  // User Menu関連
  'user-menu-trigger': 'user-menu-trigger',
  'user-menu-popup': 'user-menu-popup',
  'user-menu-profile-item': 'user-menu-profile-item',
  'user-menu-features-item': 'user-menu-features-item',
  'user-menu-signout-item': 'user-menu-signout-item',
  'user-menu-section-prefix': 'user-menu-section-',

  // Monthly Records関連
  'monthly-page': 'monthly-page',
  'monthly-tab-summary': 'monthly-tab-summary',
  'monthly-tab-detail': 'monthly-tab-detail',
  'monthly-tab-pdf': 'monthly-tab-pdf',
  'monthly-summary-table': 'monthly-summary-table',
  'monthly-summary-search': 'monthly-summary-search',
  'monthly-summary-month-select': 'monthly-summary-month-select',
  'monthly-summary-rate-filter': 'monthly-summary-rate-filter',
  'monthly-summary-reaggregate-btn': 'monthly-summary-reaggregate-btn',
  'monthly-summary-status': 'monthly-summary-status',
  'monthly-detail-user-select': 'monthly-detail-user-select',
  'monthly-detail-month-select': 'monthly-detail-month-select',
  'monthly-detail-records-table': 'monthly-detail-records-table',
  'monthly-detail-empty-state': 'monthly-detail-empty-state',
  'monthly-detail-kpi-root': 'monthly-detail-kpi-root',
  'monthly-user-detail-root': 'monthly-user-detail-root',
  'monthly-user-detail-tabs': 'monthly-user-detail-tabs',
  'monthly-user-detail-tab-basic': 'monthly-user-detail-tab-basic',
  'monthly-user-detail-tab-billing': 'monthly-user-detail-tab-billing',
  'monthly-user-detail-mounted': 'monthly-user-detail-mounted',
  'monthly-user-detail-effective-params': 'monthly-user-detail-effective-params',
  'monthly-pdf-generate-btn': 'monthly-pdf-generate-btn',
  'monthly-pdf-panel': 'monthly-pdf-panel',
  'monthly-pdf-download-btn': 'monthly-pdf-download-btn',

  // Mobile Agenda View
  'mobile-agenda-loading': 'mobile-agenda-loading',
  'mobile-agenda-error': 'mobile-agenda-error',
  'mobile-agenda-empty': 'mobile-agenda-empty',
  'mobile-agenda-container': 'mobile-agenda-container',
  'mobile-agenda-schedule-item': 'mobile-agenda-schedule-item',
  'mobile-agenda-schedule-conflict': 'mobile-agenda-schedule-conflict',

  // Agenda / Handoff Timeline
  'agenda-page-root': 'agenda-page-root',
  'agenda-timeline-list': 'agenda-timeline-list',
  'agenda-timeline-item': 'agenda-timeline-item',
  'agenda-filter-morning': 'agenda-filter-morning',
  'agenda-filter-evening': 'agenda-filter-evening',

  // Support Plan Guide HUD
  'support-plan-hud': 'support-plan-hud',
  'support-plan-updated': 'support-plan-updated',
  'monitoring-evidence-section': 'monitoring-evidence-section',
  'support-plan-goal-icon': 'support-plan-goal-icon',
  'support-plan-risk-icon': 'support-plan-risk-icon',
} as const;

type LeafValues<T> = T extends string
  ? T
  : T extends Record<string, unknown>
    ? LeafValues<T[keyof T]>
    : never;

// 🔧 型安全なTestID型を定義
export type TestId = LeafValues<typeof TESTIDS>;

// React で使うお手軽ヘルパー（型安全版でタイポ防止）
export function tid(id: TestId) {
  return { 'data-testid': id } as const;
}

// プレフィックス + サフィックスを安全に扱うヘルパー
export function tidWithSuffix(id: TestId, suffix: string) {
  return { 'data-testid': `${id}${suffix}` };
}
