name: Contracts :: Pact Provider

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment for can-i-deploy (eg. staging, prod)"
        required: true
        default: "staging"
      participant:
        description: "Override provider pacticipant name (optional)"
        required: false
        default: ""
      version:
        description: "Override provider version (defaults to commit SHA)"
        required: false
        default: ""
      allowBrokerFallback:
        description: "Allow deploy when broker is unreachable (not recommended)"
        required: false
        default: "false"

concurrency:
  group: pact-provider-${{ github.ref || github.run_id }}
  cancel-in-progress: true

env:
  NODE_VERSION: "20"

jobs:
  can_i_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
      - name: Install deps
        run: npm ci
      - name: can-i-deploy (provider)
        env:
          PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
          PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
          PACT_PACTICIPANT: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.participant != '' && github.event.inputs.participant) || vars.PACT_PROVIDER_NAME }}
          PACT_APP_VERSION: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.version != '' && github.event.inputs.version) || github.sha }}
          PACT_ENV: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.environment) || 'staging' }}
          PACT_CAN_I_DEPLOY_ALLOW_BROKER_FAILURE: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.allowBrokerFallback == 'true') || vars.PACT_CAN_I_DEPLOY_ALLOW_BROKER_FAILURE == 'true' }}
        run: npm run contracts:pact:can-i-deploy
      - name: can-i-deploy summary
        if: always()
        env:
          SUMMARY_ENV: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.environment) || 'staging' }}
          SUMMARY_VERSION: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.version != '' && github.event.inputs.version) || github.sha }}
        run: |
          {
            echo "## can-i-deploy (provider)";
            echo "";
            echo "- Target environment: ${SUMMARY_ENV}";
            echo "- Version: ${SUMMARY_VERSION}";
          } >> "${GITHUB_STEP_SUMMARY}"
