name: Label Schema Changes

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Detect schema-related changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            schema:
              - 'provision/**'
              - 'scripts/provision-spo.ps1'
              - '.github/workflows/provision-sharepoint.yml'
      - name: Add schema label
        if: steps.filter.outputs.schema == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request?.number;
            if (!pr) return;
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr,
              labels: ['schema']
            });
