name: Provision Apply (PR/Main)

on:
  # 明示実行（安全）
  workflow_dispatch:
    inputs:
      siteRelativeUrl:
        description: "SITE_RELATIVE_URL (e.g. /sites/welfare)"
        required: false
        default: "/sites/welfare"
      addTopNavigation:
        description: "Also add links to Top Navigation"
        required: false
        type: boolean
        default: false
  # PRに 'apply' ラベルが付いているときだけ実行
  pull_request:
    types: [opened, reopened, synchronize, labeled]
    branches: [ main ]
    paths:
      - 'provision/**'
      - 'scripts/provision-spo.ps1'
      - '.github/workflows/provision-apply.yml'
      - 'docs/provisioning.md'
  # main へマージされたら自動適用（任意・要件に応じてコメントアウト可）
  push:
    branches: [ main ]
    paths:
      - 'provision/**'
      - 'scripts/provision-spo.ps1'

jobs:
  provision-apply:
    # PRの場合は 'apply' ラベルが必須。手動 dispatch は常にOK。
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' &&
       contains(github.event.pull_request.labels.*.name, 'apply')) ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest

    # 事故防止に「環境」保護を推奨（Settings > Environments で reviewers を設定）
    environment: sharepoint-prod

    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node (for tooling if needed)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Guard Set-ListFieldSafe signature
        shell: pwsh
        run: |
          if (Select-String -Path scripts/provision-spo.ps1 -Pattern '\[bool\]\$WhatIf' -Quiet) {
            throw 'Set-ListFieldSafe still accepts [bool]$WhatIf (old script)'
          }
          if (Select-String -Path scripts/provision-spo.ps1 -Pattern 'Set-ListFieldSafe[^\n]*-WhatIf' -Quiet) {
            throw 'Set-ListFieldSafe call still passes -WhatIf (old script)'
          }

      - name: Install PowerShell module (PnP v3)
        shell: pwsh
        run: |
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          Install-Module PnP.PowerShell -Scope CurrentUser -Force -AllowClobber
          Import-Module PnP.PowerShell
          Write-Host "PnP.PowerShell version:"; (Get-Module PnP.PowerShell).Version
          Write-Host "Has New-PnPList?"; Get-Command -Module PnP.PowerShell New-PnPList | Format-Table -AutoSize

      - name: Decode certificate (if provided)
        id: cert
        shell: pwsh
        env:
          RAW_CERT: ${{ secrets.SPO_CERT_BASE64 }}
        run: |
          if ([string]::IsNullOrWhiteSpace($env:RAW_CERT)) {
            Write-Host 'No certificate secret provided. Skipping.'
            return
          }

          $normalized = ($env:RAW_CERT -replace '\s', '')
          try {
            $bytes = [Convert]::FromBase64String($normalized)
          } catch {
            throw "Failed to decode SPO_CERT_BASE64: $($_.Exception.Message)"
          }

          $outPath = Join-Path $env:RUNNER_TEMP 'spoCert.pfx'
          [IO.File]::WriteAllBytes($outPath, $bytes)

          if (-not (Test-Path $outPath) -or (Get-Item $outPath).Length -eq 0) {
            throw 'Decoded certificate file is empty.'
          }

          "path=$outPath" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: "Provision (APPLY: WhatIf=false)"
        shell: pwsh
        env:
          AAD_TENANT_ID: ${{ secrets.AAD_TENANT_ID }}
          AAD_APP_ID: ${{ secrets.AAD_APP_ID }}
          SPO_CERT_PASSWORD: ${{ secrets.SPO_CERT_PASSWORD }}
          SPO_CLIENT_SECRET: ${{ secrets.SPO_CLIENT_SECRET }}
          SPO_RESOURCE: ${{ secrets.SPO_RESOURCE }}
          SPO_CERT_PATH: ${{ steps.cert.outputs.path }}
          SITE_RELATIVE_URL_SECRET: ${{ github.event.inputs.siteRelativeUrl }}
          ADD_TOP_NAV: ${{ github.event_name == 'workflow_dispatch' && inputs.addTopNavigation }}
        run: |
          $ErrorActionPreference = 'Stop'
          Import-Module PnP.PowerShell -ErrorAction Stop

          if (-not $env:SPO_RESOURCE) { throw 'SPO_RESOURCE secret is required (e.g. https://<tenant>.sharepoint.com)' }
          # workflow_dispatch の入力を最優先し、空ならシークレット/既定値を使用
          $siteRel = '${{ inputs.siteRelativeUrl }}'
          if ([string]::IsNullOrWhiteSpace($siteRel)) {
            $siteRel = if ($env:SITE_RELATIVE_URL_SECRET) { $env:SITE_RELATIVE_URL_SECRET } else { '/sites/welfare' }
          }
          $siteUrl = "$($env:SPO_RESOURCE)$siteRel"

          if ((Test-Path $env:SPO_CERT_PATH) -and $env:SPO_CERT_PASSWORD) {
            $sec = ConvertTo-SecureString $env:SPO_CERT_PASSWORD -AsPlainText -Force
            Connect-PnPOnline -Url $siteUrl -ClientId $env:AAD_APP_ID -Tenant $env:AAD_TENANT_ID -CertificatePath $env:SPO_CERT_PATH -CertificatePassword $sec
          } elseif ($env:SPO_CLIENT_SECRET) {
            $sec = ConvertTo-SecureString $env:SPO_CLIENT_SECRET -AsPlainText -Force
            Connect-PnPOnline -Url $siteUrl -ClientId $env:AAD_APP_ID -Tenant $env:AAD_TENANT_ID -ClientSecret $sec
          } else {
            throw 'Provide SPO_CERT_BASE64+SPO_CERT_PASSWORD or SPO_CLIENT_SECRET as GitHub Secrets.'
          }

          Write-Host "Script SHA: $env:GITHUB_SHA"
          Write-Host "Top of scripts/provision-spo.ps1:"
          Get-Content scripts/provision-spo.ps1 | Select-Object -First 40

          ./scripts/provision-spo.ps1 `
            -SiteUrl $siteUrl `
            -RecreateExisting:$false `
            -ApplyFieldUpdates:$true `
            -ForceTypeReplace:$false `
            -WhatIfMode:$false `
            -SchemaPath provision/schema.xml `
            -ChangesOutPath 'provision/changes.json' `
            -EmitChanges

      - name: Update navigation links
        if: success()
        shell: pwsh
        env:
          AAD_TENANT_ID: ${{ secrets.AAD_TENANT_ID }}
          AAD_APP_ID: ${{ secrets.AAD_APP_ID }}
          SPO_CERT_PASSWORD: ${{ secrets.SPO_CERT_PASSWORD }}
          SPO_CLIENT_SECRET: ${{ secrets.SPO_CLIENT_SECRET }}
          SPO_RESOURCE: ${{ secrets.SPO_RESOURCE }}
          SPO_CERT_PATH: ${{ steps.cert.outputs.path }}
          SITE_RELATIVE_URL_SECRET: ${{ github.event.inputs.siteRelativeUrl }}
          ADD_TOP_NAV: ${{ github.event_name == 'workflow_dispatch' && inputs.addTopNavigation }}
        run: |
          $ErrorActionPreference = 'Stop'
          Import-Module PnP.PowerShell -ErrorAction Stop

          if (-not $env:SPO_RESOURCE) { throw 'SPO_RESOURCE secret is required (e.g. https://<tenant>.sharepoint.com)' }

          $siteRel = '${{ inputs.siteRelativeUrl }}'
          if ([string]::IsNullOrWhiteSpace($siteRel)) {
            $siteRel = if ($env:SITE_RELATIVE_URL_SECRET) { $env:SITE_RELATIVE_URL_SECRET } else { '/sites/welfare' }
          }
          $siteUrl = "$($env:SPO_RESOURCE)$siteRel"

          $arguments = @('-SiteUrl', $siteUrl, '-TenantId', $env:AAD_TENANT_ID, '-ClientId', $env:AAD_APP_ID)

          if ($env:SPO_CLIENT_SECRET) {
            $arguments += @('-ClientSecret', $env:SPO_CLIENT_SECRET)
          }

          if ($env:SPO_CERT_PATH -and (Test-Path $env:SPO_CERT_PATH)) {
            if ($env:SPO_CERT_PASSWORD) {
              $secureCert = ConvertTo-SecureString $env:SPO_CERT_PASSWORD -AsPlainText -Force
              $arguments += @('-CertificatePath', $env:SPO_CERT_PATH, '-CertificatePassword', $secureCert)
            } else {
              $arguments += @('-CertificatePath', $env:SPO_CERT_PATH)
            }
          }

          if ([string]::Equals($env:ADD_TOP_NAV, 'true', [System.StringComparison]::OrdinalIgnoreCase)) {
            $arguments += '-AddTopNav'
          }

          & ./scripts/add-nav.ps1 @arguments

      - name: Upload changes.json artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: provision-changes
          path: ${{ github.workspace }}/provision/changes.json
          if-no-files-found: ignore
